### ISSUE TITLE
使用voice conversion报ERROR

### ISSUE THREAD

**Issue by swoloka** [Plachtaa/VITS-fast-fine-tuning#100]
```
To create a public link, set `share=True` in `launch()`.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.gradio.app:443
DEBUG:pydub.converter:subprocess.call(['ffmpeg', '-y', '-i', 'C:\\Users\\XXXX\\AppData\\Local\\Temp\\audio7bj639u8.wav', '-acodec', 'pcm_s32le', '-vn', '-f', 'wav', '-'])
Traceback (most recent call last):
  File "gradio\routes.py", line 380, in run_predict
    event_id=event_id,
  File "gradio\blocks.py", line 1018, in process_api
    fn_index, inputs, iterator, request, event_id
  File "gradio\blocks.py", line 836, in call_function
    fn, *processed_input, limiter=self.limiter
  File "anyio\to_thread.py", line 32, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "inference.py", line 54, in vc_fn
  File "utils.py", line 257, in __getitem__
AttributeError: 'HParams' object has no attribute 'User'
```
已经装了ffmpeg

**Comment by Plachtaa** [comment]
不存在于模型中的角色是不能转换的

**Comment by swoloka** [comment]
> 

所以是被转换的也需要有模型吗

**Comment by swoloka** [comment]
source speaker我没选来着

**Comment by Plachtaa** [comment]
都要指定才行
