### ISSUE TITLE
inference报错

### ISSUE THREAD

**Issue by dasudiy** [Plachtaa/VITS-fast-fine-tuning#112]
模型是使用15分钟的英文长音频训练的，目测一切正常，拿到文件后按要求放置，路径无中文，启动inference.exe后，在WEB界面输入任何中日英任意内容均报错，信息如下
```
Traceback (most recent call last):
  File "gradio\routes.py", line 380, in run_predict
    event_id=event_id,
  File "gradio\blocks.py", line 1018, in process_api
    fn_index, inputs, iterator, request, event_id
  File "gradio\blocks.py", line 836, in call_function
    fn, *processed_input, limiter=self.limiter
  File "anyio\to_thread.py", line 32, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "inference.py", line 36, in tts_fn
  File "inference.py", line 25, in get_text
  File "text\__init__.py", line 21, in text_to_sequence
  File "text\__init__.py", line 55, in _clean_text
AttributeError: module 'text.cleaners' has no attribute 'english_cleaners'
```
使用的版本是release中的v1.1，谢谢

**Comment by Plachtaa** [comment]
你的配置文件(.json)可否看一下

**Comment by dasudiy** [comment]
是这个吗 `finetune_speaker.json` ?
```json
{
  "train": {
    "log_interval": 100,
    "eval_interval": 1000,
    "seed": 1234,
    "epochs": 10000,
    "learning_rate": 0.0002,
    "betas": [
      0.8,
      0.99
    ],
    "eps": 1e-09,
    "batch_size": 16,
    "fp16_run": true,
    "lr_decay": 0.999875,
    "segment_size": 8192,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0
  },
  "data": {
    "training_files": "final_annotation_train.txt",
    "validation_files": "final_annotation_val.txt",
    "text_cleaners": [
      "english_cleaners"
    ],
    "max_wav_value": 32768.0,
    "sampling_rate": 22050,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": true,
    "n_speakers": 4,
    "cleaned_text": true
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [
      3,
      7,
      11
    ],
    "resblock_dilation_sizes": [
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ]
    ],
    "upsample_rates": [
      8,
      8,
      2,
      2
    ],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [
      16,
      16,
      4,
      4
    ],
    "n_layers_q": 3,
    "use_spectral_norm": false,
    "gin_channels": 256
  },
  "symbols": [
    "_",
    ",",
    ".",
    "!",
    "?",
    "-",
    "~",
    "\u2026",
    "N",
    "Q",
    "a",
    "b",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "\u0251",
    "\u00e6",
    "\u0283",
    "\u0291",
    "\u00e7",
    "\u026f",
    "\u026a",
    "\u0254",
    "\u025b",
    "\u0279",
    "\u00f0",
    "\u0259",
    "\u026b",
    "\u0265",
    "\u0278",
    "\u028a",
    "\u027e",
    "\u0292",
    "\u03b8",
    "\u03b2",
    "\u014b",
    "\u0266",
    "\u207c",
    "\u02b0",
    "`",
    "^",
    "#",
    "*",
    "=",
    "\u02c8",
    "\u02cc",
    "\u2192",
    "\u2193",
    "\u2191",
    " "
  ],
  "speakers": {
    "output": 0,
    "specialweek": 1,
    "zhongli": 2,
    "vctk": 3
  }
}
```

**Comment by Plachtaa** [comment]
你的cleaner名字为什么是`english_cleaners`

**Comment by dasudiy** [comment]
> 你的cleaner名字为什么是`english_cleaners`

噗……我的锅……我之前试图把模型放进原版里面合成，结果里面没有`cjke_cleaners2`。不好意思，妥妥的。

**Comment by dasudiy** [comment]
但是英文发音也忒奇怪了，是需要改什么配置吗？

**Comment by Plachtaa** [comment]
这模型本身英文水平就不是很好，没有办法

**Comment by dasudiy** [comment]
了解，多谢。
