### ISSUE TITLE
我看今天colab更新了.但是有点小问题.

### ISSUE THREAD

**Issue by tencentdosos** [Plachtaa/VITS-fast-fine-tuning#113]
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/denoise_audio.py", line 12, in <module>
    wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
  File "/usr/local/lib/python3.9/dist-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/usr/local/lib/python3.9/dist-packages/torchaudio/io/_compat.py", line 103, in load_audio
    s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
RuntimeError: Failed to open the input "./separated/htdemucs/adao_3/vocals.wav" (No such file or directory).

Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/long_audio_transcribe.py", line 31, in <module>
    model = whisper.load_model(args.whisper_size)
  File "/usr/local/lib/python3.9/dist-packages/whisper/__init__.py", line 131, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/usr/local/lib/python3.9/dist-packages/whisper/__init__.py", line 76, in _download
    buffer = source.read(8192)
  File "/usr/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

之前的时候是没有这个问题的.这次修改之后有了这个.

**Comment by tencentdosos** [comment]
我找到问题了,有个视频太大了,转换出了问题.但是不知道为啥之前没事...可能是环境的bug

**Comment by tencentdosos** [comment]
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/long_audio_transcribe.py", line 41, in <module>
    if result['language'] not in list(lang2token.keys()):
NameError: name 'lang2token' is not defined
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.
还是不行..不知道为啥..
