### ISSUE TITLE
inference.exe ERROR

### ISSUE THREAD

**Issue by Anonym0us33** [Plachtaa/VITS-fast-fine-tuning#126]
```
  File "inference.py", line 86, in <module>
  File "utils.py", line 194, in get_hparams_from_file
FileNotFoundError: [Errno 2] No such file or directory: './finetune_speaker.json'
[18808] Failed to execute script 'inference' due to unhandled exception!
```

**Comment by Plachtaa** [comment]
先读读README吧，你不放config文件当然打不开

**Comment by TakanashiYune** [comment]
> I'm getting a similar issue trying to run a 4.0 voice. The voice run perfectly on SO-VITS-SVC-FORK, but I'm getting a symbols error:
> 
> Traceback (most recent call last): File "inference.py", line 90, in AttributeError: 'HParams' object has no attribute 'symbols' [7748] Failed to execute script 'inference' due to unhandled exception!

me too
