### ISSUE TITLE
运行inference.exe后无反应

### ISSUE THREAD

**Issue by CYunsen** [Plachtaa/VITS-fast-fine-tuning#132]
文件摆放方式符合要求，但是无论怎么启动inference.exe浏览器都没有反应

**Comment by Plachtaa** [comment]
在命令行运行inference.exe看一下具体报错信息

**Comment by CYunsen** [comment]
> 在命令行运行inference.exe看一下具体报错信息
我直接复制最后一部分了
Traceback (most recent call last):
  File "inference.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "text\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "text\cleaners.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "text\mandarin.py", line 9, in <module>
  File "jieba\__init__.py", line 398, in load_userdict
FileNotFoundError: [Errno 2] No such file or directory: './jieba/dict.txt'
[16332] Failed to execute script 'inference' due to unhandled exception!

**Comment by silendir** [comment]
执行inference.py和inference.exe的效果是不是一样的?

**Comment by Plachtaa** [comment]
这个真的很奇怪，有些人可以运行有些人就会报这个错，目前也没有找到该问题的解决方案。可以暂时先用MoeGoe

**Comment by CYunsen** [comment]
> 这个真的很奇怪，有些人可以运行有些人就会报这个错，目前也没有找到该问题的解决方案。可以暂时先用MoeGoe

好吧，我去看看怎么用的
