### ISSUE TITLE
本地fine-tuning时报张量形状不对

### ISSUE THREAD

**Issue by YaokaiCheng** [Plachtaa/VITS-fast-fine-tuning#139]
我正在参照colab的环境搭建本地fine-tuning环境，在训练时报了张量形状不对，之前的步骤都正常
```
(base) cheng@Denny:/mnt/e/code/VITS-fast-fine-tuning-main$ python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs "40" --drop_speaker_embed True
INFO:OUTPUT_MODEL:{'train': {'log_interval': 100, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 2, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'qirui': 0, 'zhongli': 1}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 40, 'drop_speaker_embed': True}
WARNING:OUTPUT_MODEL:/mnt/e/code/VITS-fast-fine-tuning-main is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./pretrained_models/G_0-p.pth
INFO:OUTPUT_MODEL:Loaded checkpoint './pretrained_models/G_0-p.pth' (iteration None)
./pretrained_models/D_0-p.pth
INFO:OUTPUT_MODEL:Loaded checkpoint './pretrained_models/D_0-p.pth' (iteration None)
  0%|                                                                                                                                                        | 0/18 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/e/code/VITS-fast-fine-tuning-main/finetune_speaker_v2.py", line 321, in <module>
    main()
  File "/mnt/e/code/VITS-fast-fine-tuning-main/finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/e/code/VITS-fast-fine-tuning-main/finetune_speaker_v2.py", line 134, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/mnt/e/code/VITS-fast-fine-tuning-main/finetune_speaker_v2.py", line 154, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cheng/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/mnt/e/code/VITS-fast-fine-tuning-main/data_utils.py", line 130, in __call__
    torch.LongTensor([x[1].size(1) for x in batch]),
  File "/mnt/e/code/VITS-fast-fine-tuning-main/data_utils.py", line 130, in <listcomp>
    torch.LongTensor([x[1].size(1) for x in batch]),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

版本：
操作系统：wsl2
torch：1.13
cuda：11.7

**Comment by YaokaiCheng** [comment]
问题应该出在从dataloader中取数据的时候

**Comment by HuaHuaY** [comment]
遇到的同样的问题，用的python3.8/3.10，torch 2.0。在torch2.0里，`torch.stft`函数必须指定`return_complex`参数，否则会报Error。在`return_complex=True`时报`Dimension out of range (expected to be in range of [-1, 0], but got 1)`，`return_complex=False`时正常运行。
