### ISSUE TITLE
训练时 Could not find TensorRT 报错

### ISSUE THREAD

**Issue by TwistedTale** [Plachtaa/VITS-fast-fine-tuning#147]
所有准备工作做好后开始训练时找不到 TensorRT，昨天使用的时候没有任何问题今天一摸一样的步骤一直训练出错

```
2023-04-04 00:46:09.735400: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-04 00:46:10.680835: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 00:46:18.384592: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO:output:{'train': {'log_interval': 100, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['cjke_cleaners2'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 4, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'N', 'Q', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ɑ', 'æ', 'ʃ', 'ʑ', 'ç', 'ɯ', 'ɪ', 'ɔ', 'ɛ', 'ɹ', 'ð', 'ə', 'ɫ', 'ɥ', 'ɸ', 'ʊ', 'ɾ', 'ʒ', 'θ', 'β', 'ŋ', 'ɦ', '⁼', 'ʰ', '`', '^', '#', '*', '=', 'ˈ', 'ˌ', '→', '↓', '↑', ' '], 'speakers': {'hutao': 0, 'specialweek': 1, 'zhongli': 2, 'vctk': 3}, 'model_dir': '/content/drive/MyDrive/output', 'max_epochs': 40, 'drop_speaker_embed': True}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO:output:Loaded checkpoint './pretrained_models/G_0.pth' (iteration 419)
INFO:output:Loaded checkpoint './pretrained_models/D_0.pth' (iteration 419)
  0% 0/94 [00:00<?, ?it/s]2023-04-04 00:46:34.711061: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-04 00:46:41.186625: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  0% 0/94 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 321, in <module>
    main()
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 134, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 154, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/usr/local/lib/python3.9/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/dist-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/VITS-fast-fine-tuning/data_utils.py", line 109, in __getitem__
    return self.get_audio_text_speaker_pair(self.audiopaths_sid_text[index])
  File "/content/VITS-fast-fine-tuning/data_utils.py", line 67, in get_audio_text_speaker_pair
    spec, wav = self.get_audio(audiopath)
  File "/content/VITS-fast-fine-tuning/data_utils.py", line 84, in get_audio
    spec = spectrogram_torch(audio_norm, self.filter_length,
  File "/content/VITS-fast-fine-tuning/mel_processing.py", line 66, in spectrogram_torch
    spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
  File "/usr/local/lib/python3.9/dist-packages/torch/functional.py", line 641, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.
```

**Comment by doxtor6** [comment]
一样的问题

**Comment by SULIWA** [comment]
mel_processing.py
line66 and line 104 的 torch.stft函数最后加return_complex=False
能跑，但没测试效果如何

**Comment by TwistedTale** [comment]
> 
我是在colab上跑的

**Comment by SULIWA** [comment]
> > 
> 
> 我是在colab上跑的

左边栏可以打开文件列表，到VITS-fast-fine-tuning文件夹里找到那个文件，双击后可以修改

**Comment by TwistedTale** [comment]
> > > 
> > 
> > 
> > 我是在colab上跑的
> 
> 左边栏可以打开文件列表，到VITS-fast-fine-tuning文件夹里找到那个文件，双击后可以修改

好的我试一下

**Comment by Plachtaa** [comment]
感谢提醒。经排查是因为colab自动升级到了pytorch 2.0导致的，现在已经添加了版本指定，经测试已经没有问题了

**Comment by TwistedTale** [comment]
> 感谢提醒。经排查是因为colab自动升级到了pytorch 2.0导致的，现在已经添加了版本指定，经测试已经没有问题了

多谢 👍 

还有一个和这个问题无关的问题，目前现在有没有可以用finetune模型的voice changer

**Comment by Plachtaa** [comment]
你是说变声器吗？那种东西如果要做实时的话可能比较麻烦，暂时没有
