### ISSUE TITLE
ModuleNotFoundError: No module named 'monotonic_align.core'

### ISSUE THREAD

**Issue by Nilok7** [Plachtaa/VITS-fast-fine-tuning#166]
I'm running into an error when I try and run the cmd_inference.py with all the command line arguments on a known good SO-VITS-SVC-4.0 model.

I'm getting the error:
```
Traceback (most recent call last):
  File "I:\AIStuff\VoiceChanger\VITS-fast-fine-tuning\cmd_inference.py", line 22, in <module>
    from models import SynthesizerTrn
  File "I:\AIStuff\VoiceChanger\VITS-fast-fine-tuning\models.py", line 10, in <module>
    import monotonic_align
  File "I:\AIStuff\VoiceChanger\VITS-fast-fine-tuning\monotonic_align\__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align'
```

I've tried building monotronic_align.core manually in every way I can, but it just can't find the module.

**Comment by mzltest** [comment]
也遇到了，只不过我是把VC_inference.py改名成app.py试试能不能在huggingface space上跑。本地跑没问题（用的colab的命令编译的）
Same here,though I used VC_inference.py and changed the name into app.py to see whether it runs on hugging face,however my local environment is fine (using the colab build commands)

本地build一次把monotonic_align目录下的文件commit到space也不行
I build on my local machine and upload the files to hfspace didnt work either

对应文件貌似就是一个so文件，具体不清楚，我只会用colab一键版
```
-rwxr-xr-x 1 root root 1105512 Apr 11 15:30 monotonic_align/monotonic_align/core.cpython-39-x86_64-linux-gnu.so
```

**Comment by himekifee** [comment]
```
cd monotonic_align
python setup.py build_ext --inplace
```
If it complains about no such file or directory then create a `monotonic_align` dir under `monotonic_align` dir so `monotonic_align/monotonic_align`.
