### ISSUE TITLE
步骤4报错

### ISSUE THREAD

**Issue by RhyeC** [Plachtaa/VITS-fast-fine-tuning#18]
步骤3：
Your-zip-file.zip(application/x-zip-compressed) - 9877593 bytes, last modified: 2023/2/24 - 100% done
Saving Your-zip-file.zip to Your-zip-file.zip
Archive:  ./custom_character_voice/custom_character_voice.zip
   creating: ./custom_character_voice/Your-zip-file/
   creating: ./custom_character_voice/Your-zip-file/RPK16/
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_ALLHALLOWS_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_BREAK_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_BUILDOVER_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_COMBINE_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_DIALOGUE1_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_DIALOGUE3_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_FEED_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_FORMATION_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_GAIN_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_GOATTACK_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_HELLO_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_LOADING_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_MEET_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_NEWYEAR_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_OPERATIONBEGIN_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_OPERATIONOVER_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_RETREAT_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_TIP_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_VALENTINE_JP.wav  
  inflating: ./custom_character_voice/Your-zip-file/RPK16/RPK16_WIN_JP.wav  
2023-02-24 00:46:22.335055: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-24 00:46:23.282110: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-24 00:46:23.282236: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-02-24 00:46:23.282258: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
finished

步骤4节选：
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/finetune_speaker.py", line 133, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/finetune_speaker.py", line 241, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "/content/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/VITS_voice_conversion/finetune_speaker.py", line 279, in evaluate
    y_hat, attn, mask, *_ = generator.module.infer(x, x_lengths, speakers, max_len=1000)
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by RhyeC** [comment]
音频文件夹：
![znd](https://user-images.githubusercontent.com/126213217/221066793-cec1545b-74da-4043-b1a8-b64beaa30d2d.jpg)

**Comment by Plachtaa** [comment]
有可能是文件结构问题，方便上传一下你的zip文件吗？我试试复现一下，如果是bug我会尽快修复

**Comment by Plachtaa** [comment]
文件结构问题，参见[#4](https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/4)

**Comment by RhyeC** [comment]
> 文件结构问题，参见[#4](https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/4)

不好意思我没有搞懂。看说法应该是zip——zip内各个需要添加的角色的文件夹——角色文件夹内的数个语音，是我理解有错误吗？

**Comment by Plachtaa** [comment]
[dingzhentaffy.zip](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10820246/dingzhentaffy.zip)
我上传了一个样本，你参照一下格式好了

**Comment by RhyeC** [comment]
> [dingzhentaffy.zip](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10820246/dingzhentaffy.zip) 我上传了一个样本，你参照一下格式好了

非常感谢！
