### ISSUE TITLE
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'

### ISSUE THREAD

**Issue by Naozumi520** [Plachtaa/VITS-fast-fine-tuning#207]
```
\\Mac\Home\Downloads\100 ep>\\Mac\Home\Downloads\MoeGoe\MoeGoe.exe
Path of a VITS model: \\Mac\Home\Downloads\100 ep\G_latest.pth
Path of a config file: \\Mac\Home\Downloads\100 ep\moegoe_config.json
TTS or VC? (t/v):v
Path of an audio file to convert:
\\Mac\Home\Downloads\so-vits-svc-4.0\raw\idol.wav
ID      Speaker
0       naozumi
Original speaker ID: 0
Target speaker ID: 0
Path to save: test_may.wav
min value is  tensor(-1.3357)
max value is  tensor(1.3094)
Traceback (most recent call last):
  File "MoeGoe.py", line 166, in <module>
  File "MoeGoe.py", line 127, in voice_conversion
  File "models.py", line 397, in voice_conversion
  File "torch\nn\modules\module.py", line 1208, in __getattr__
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'
[6296] Failed to execute script 'MoeGoe' due to unhandled exception!
```

**Comment by eve2ptp** [comment]
以前复现的时候遇到过，但不知道怎么解决

使用 C 模型，不勾选 ADD_AUXILIARY，生成 G_latest.pth 后推理的时候就会报这个错

```python
Traceback (most recent call last):
  File "E:\Code\Python\blivedm\AI_Voice\VITS_fast_fine_tuning\api.py", line 199, in <module>
    audio = load_fast_vits(text)
  File "E:\Code\Python\blivedm\AI_Voice\VITS_fast_fine_tuning\api.py", line 136, in load_fast_vits
    net_g.infer(
  File "E:\Code\Python\blivedm\AI_Voice\VITS_fast_fine_tuning\models_infer.py", line 370, in infer
    g = self.emb_g(sid).unsqueeze(-1) # [b, h, 1]
  File "D:\pyenvs\voice\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'
```
