### ISSUE TITLE
colab在线训练报错相关问题。

### ISSUE THREAD

**Issue by SS4x13** [Plachtaa/VITS-fast-fine-tuning#215]
我进入大佬提供的笔记本后，目前遇到两个问题，一是安装环境依赖时，pyopenjtalk安装错误，imageio版本要大于等于2.5才能安装moviepy，然后这一步似乎没有安装whisper和Demucs，在自动处理数据那一步时会出现没有whisper module的问题。但是我在第一步增加了pip install whisper后，在自动处理数据时又会说“AttributeError: module 'whisper' has no attribute 'load_model'”。

感觉问题多多，还请大佬解惑。谢谢！

**Comment by SS4x13** [comment]
另外就是，如果可能的话，希望大佬出一个本地训练的教程。我想练的角色有大约40分钟的音频，笔记本线上是不是只能低于20分钟？

**Comment by 40740** [comment]
> 我进入大佬提供的笔记本后，目前遇到两个问题，一是安装环境依赖时，pyopenjtalk安装错误，imageio版本要大于等于2.5才能安装moviepy，然后这一步似乎没有安装whisper和Demucs，在自动处理数据那一步时会出现没有whisper module的问题。但是我在第一步增加了pip install whisper后，在自动处理数据时又会说“AttributeError: module 'whisper' has no attribute 'load_model'”。
> 
> 感觉问题多多，还请大佬解惑。谢谢！

同样的问题，昨天晚上还好好的，早上就挂了。

**Comment by Telajipai** [comment]
> 我进入大佬提供的笔记本后，目前遇到两个问题，一是安装环境依赖时，pyopenjtalk安装错误，imageio版本要大于等于2.5才能安装moviepy，然后这一步似乎没有安装whisper和Demucs，在自动处理数据那一步时会出现没有whisper module的问题。但是我在第一步增加了pip install whisper后，在自动处理数据时又会说“AttributeError: module 'whisper' has no attribute 'load_model'”。
> 
> 感觉问题多多，还请大佬解惑。谢谢！

我也是！在大概27号十点左右就开始报错了，我之前一直运行的很流畅

**Comment by Plachtaa** [comment]
了解了，正在排查问题，解决之后会在这里告知你

**Comment by Plachtaa** [comment]
经排查是由于colab自动升级到了python3.10导致的，正在尝试修复

**Comment by Plachtaa** [comment]
问题已修复，colab笔记本现在可以正常使用了。本地训练教程写起来比较花时间，但是会考虑的

**Comment by huzhugongsheng** [comment]
> 问题已修复，colab笔记本现在可以正常使用了。本地训练教程写起来比较花时间，但是会考虑的

感谢大佬的无私奉献，中国必将因为有了您们变得更加强大

**Comment by SS4x13** [comment]
> 问题已修复，colab笔记本现在可以正常使用了。本地训练教程写起来比较花时间，但是会考虑的

谢谢大佬！

**Comment by SS4x13** [comment]
Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 16, in <module>
    wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/io/_compat.py", line 103, in load_audio
    s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
RuntimeError: Failed to open the input "./separated/htdemucs/Gilberta/vocals.wav" (No such file or directory).
100%|█████████████████████████████████████| 2.87G/2.87G [00:50<00:00, 60.6MiB/s]
Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

大佬，在进行第三步的时候为啥说找不到文件呢。。。我确实把文件放在谷歌盘指定路径了呀，前一步2.2里也读取成功了。。。

**Comment by SS4x13** [comment]
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Downloading: "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th" to /root/.cache/torch/hub/checkpoints/955717e8-8726e21a.th
100% 80.2M/80.2M [00:00<00:00, 175MB/s]
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/VITS-fast-fine-tuning/separated/htdemucs
Separating track raw_audio/Gilberta.wav
100%|██████████████████████████████████████████████| 3065.3999999999996/3065.3999999999996 [02:16<00:00, 22.51seconds/s]
Killed
Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 16, in <module>
    wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/io/_compat.py", line 103, in load_audio
    s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
RuntimeError: Failed to open the input "./separated/htdemucs/Gilberta/vocals.wav" (No such file or directory).
100%|█████████████████████████████████████| 2.87G/2.87G [00:50<00:00, 60.6MiB/s]
Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

大佬，在进行第三步的时候为啥说找不到文件呢。。。我确实把文件放在谷歌盘指定路径了呀，前半部分"Separating track raw_audio/Gilberta.wav"也确实表明文件是存在的。。。为啥后面说没有呢。。。

**Comment by Plachtaa** [comment]
1. 命名不符合格式
2. 音频太长，就是命名没错内存也会爆

**Comment by SS4x13** [comment]
> 1. 命名不符合格式
> 2. 音频太长，就是命名没错内存也会爆

好吧。。。果然还是得本地练，本地我目前执行到这一步：
python scripts/long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
但是会报错：D:\VITS\VITS-fast-fine-tuning>python scripts/long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
transcribing ./denoised_audio/Gilberta.wav...

Traceback (most recent call last):
  File "D:\VITS\VITS-fast-fine-tuning\scripts\long_audio_transcribe.py", line 46, in <module>
    if result['language'] not in list(lang2token.keys()):
NameError: name 'lang2token' is not defined

我在“long_audio_transcribe.py ”中强行指定了
lang2token = {
            'zh': "[ZH]",
            'ja': "[JA]",
        }
后，又出现报错：D:\VITS\VITS-fast-fine-tuning>python scripts/long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
transcribing ./denoised_audio/Gilberta.wav...

ja
dict_keys(['zh', 'ja'])
Traceback (most recent call last):
  File "D:\VITS\VITS-fast-fine-tuning\scripts\long_audio_transcribe.py", line 57, in <module>
    code = file.rstrip(".wav").split("_")[1]
IndexError: list index out of range

。。。想请教大佬要怎么办o(╥﹏╥)o

**Comment by SS4x13** [comment]
仔细看了下，前面的报错好像是文件名命名没带“_”的问题。。。
不过感觉前面“args = parser.parse_args()”可能有问题，导致后面对lang2token赋值的时候有问题，我强行指定估计还是会有更多问题出来。。。

**Comment by SS4x13** [comment]
怪，左练右练，效果都不如我最开始瞎练的时候好。。。

**Comment by snakeqiuwei** [comment]
> > 1. 命名不符合格式
> > 2. 音频太长，就是命名恰好内存爆炸
> 
> 好吧。。。确实还是得本地练，本地我目前执行到这一步： python scripts/long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large 但是会报错：D:\VITS\VITS-fast-微调>python脚本/long_audio_transcribe.py --语言“{PRETRAINED_MODEL}”--whisper_size大 转录./denoished_audio/Gilberta.wav...
> 
> 回溯（最近一次调用最后一次）： 文件“D:\VITS\VITS-fast-fine-tuning\scripts\long_audio_transcribe.py”，第 46 行，在 if result['language'] not in list(lang2token.keys() ）： NameError：名称“lang2token”未定义
> 
> 我在“long_audio_transcribe.py”中强行指定了 lang2token = { 'zh': "[ZH]", 'ja': "[JA]", } 后，又出现报错：D:\VITS\VITS-fast-微调>python脚本/long_audio_transcribe.py --语言“{PRETRAINED_MODEL}”--whisper_size大 转录./denoished_audio/Gilberta.wav...
> 
> ja dict_keys(['zh', 'ja']) 回溯（最近一次调用最后一次）： 文件“D:\VITS\VITS-fast-fine-tuning\scripts\long_audio_transcribe.py”，第 57 行，代码 = 文件.rstrip(".wav").split("_")[1] IndexError: 列表索引超出范围
> 
> 。。。想请教大佬要怎么办o(╥﹏╥)o

{PRETRAINED_MODEL}替换为CJE、CJ或C
