### ISSUE TITLE
错误：ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by FrankZxShen** [Plachtaa/VITS-fast-fine-tuning#222]
感谢出色的工作！
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 133, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 153, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 988, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 598, in __init__
    self._sampler_iter = iter(self._index_sampler)
  File "/content/VITS-fast-fine-tuning/data_utils.py", line 233, in __iter__
    ids_bucket = ids_bucket + ids_bucket * (rem // len_bucket) + ids_bucket[:(rem % len_bucket)]
ZeroDivisionError: integer division or modulo by zero
```
对于这个问题，可以采用#27 的方法加入辅助数据的方法解决，我在想是否可以在[这里](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/data_utils.py#L198)修改为
`for i in range(len(buckets) - 1, -1, -1)`
这时目前我的解决方案

我正在尝试使用LoRA微调VITS，但是遇到了[同样的问题](https://github.com/nivibilla/efficient-vits-finetuning)，请问有什么好的解决方案吗？

**Comment by Plachtaa** [comment]
样本太少就会导致采样器报错，多加点样本就好了

**Comment by FrankZxShen** [comment]
感谢你的回复！ @Plachtaa 
但我仍然不知道为什么lora在VITS微调中不起作用，部分结构修改为lora结构，可以帮忙看看这样修改有什么问题吗？
```
self.emb = lora.Embedding(n_vocab, hidden_channels, r = 4)
...
self.emb_g = lora.Embedding(n_speakers, gin_channels, r = 4)
```
这是net_g修改过的结构
```
enc_p.emb.weight
enc_p.emb.lora_A
enc_p.emb.lora_B
...
emb_g.weight
emb_g.lora_A
emb_g.lora_B
```
如果需要，我可以上传完整代码。

**Comment by Plachtaa** [comment]
请问以下你说的不起作用是指可以微调但是效果不理想，还是说一直在报错呢？

**Comment by FrankZxShen** [comment]
你好！我在你的repo上进行微调时没有问题！但当我在此基础上lora微调，但我的微调效果不理想，lora微调后人物音色并未发生改变，这可能是因为只修改了先验编码器，具体原因我还不明确。
net_g中我引入了 SynthesizerTrn_lora，在先验编码器中仅修改了`self.emb = lora.Embedding(n_vocab, hidden_channels, r=4)`
并冻结其他层的权重。
模型load和save我采用[lora](https://github.com/microsoft/LoRA)的形式。
```
# Load
def load_lora_checkpoint(checkpoint_path, model, optimizer=None, generator_path = "./OUTPUT_MODEL_origin/G_latest.pth"):
  assert os.path.isfile(checkpoint_path)
  checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
  iteration = checkpoint_dict['iteration']
  learning_rate = checkpoint_dict['learning_rate']
  if optimizer is not None:
    optimizer.load_state_dict(checkpoint_dict['optimizer'])
  generator_state_dict = torch.load(generator_path)['model']
  lora_state_dict = checkpoint_dict['model']
  if hasattr(model, 'module'):
    model.module.load_state_dict(generator_state_dict, strict=False)
    model.module.load_state_dict(lora_state_dict, strict=False)
    lora.mark_only_lora_as_trainable(model.module)
  else:
    model.load_state_dict(generator_state_dict, strict=False)
    model.load_state_dict(lora_state_dict, strict=False)
    lora.mark_only_lora_as_trainable(model)
  logger.info("Loaded checkpoint '{}' (iteration {})" .format(
    checkpoint_path, iteration))

# Save
def save_lora_checkpoint(model, optimizer, learning_rate, iteration, checkpoint_path):
  logger.info("Saving model and optimizer state at iteration {} to {}".format(
    iteration, checkpoint_path))
  if hasattr(model, 'module'):
    state_dict = lora.lora_state_dict(model.module)
  else:
    state_dict = lora.lora_state_dict(model)
  torch.save({'model': state_dict,
              'iteration': iteration,
              'optimizer': optimizer.state_dict() if optimizer is not None else None,
              'learning_rate': learning_rate}, checkpoint_path)
```
训练过程中显存占用明显降低，到达同样的epoch数训练时长缩短80%，和的[这个repo](https://github.com/nivibilla/efficient-vits-finetuning)的问题类似。

**Comment by Plachtaa** [comment]
与大型Transformer不同，VITS只训练embedding是不起作用的，需要将Generator和Discriminator的所有权重一起训练才可以。

**Comment by FrankZxShen** [comment]
谢谢！我还应该再仔细阅读VITS论文。
这个issue暂时保留一下好吗，可能会继续更新相关的问题！

**Comment by zhazl** [comment]
> 

你好！有试过不冻结其他层，单纯用LoRA来尝试过效果吗？

**Comment by Plachtaa** [comment]
LoRA目前仅限于nn.Conv2d, nn.Embedding以及nn.Linear， VITS的主要生成部分是nn.Conv1d的上采样，使用LoRA不会有多大效果。并且，LoRA主要目的是降低大模型的微调成本，VITS属于小模型，最好是调所有参数以保证性能。

**Comment by FrankZxShen** [comment]
@zhazl @Plachtaa 感谢你的回复，这种方法通过实验无法达到LoRA所需的效果，仅在Text部分调整对于VITS效果是甚微的，可以参考这个[repo](https://github.com/nivibilla/efficient-vits-finetuning)出现的问题。虽然某些论文证明LoRA用于TTS微调是合理的，但是仍需要进一步研究。
