### ISSUE TITLE
笔记运行报错step3

### ISSUE THREAD

**Issue by T-huangzm** [Plachtaa/VITS-fast-fine-tuning#229]
MoviePy - Writing audio in ./raw_audio/xi_594131.wav
MoviePy - Done.
Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 3, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so: undefined symbol: PyObject_GET_WEAKREFS_LISTPTR
Traceback (most recent call last):
  File "scripts/long_audio_transcribe.py", line 2, in <module>
    import whisper
  File "/usr/local/lib/python3.8/dist-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so: undefined symbol: PyObject_GET_WEAKREFS_LISTPTR
Traceback (most recent call last):
  File "scripts/short_audio_transcribe.py", line 1, in <module>
    import whisper
  File "/usr/local/lib/python3.8/dist-packages/whisper/__init__.py", line 8, in <module>
    import torch
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so: undefined symbol: PyObject_GET_WEAKREFS_LISTPTR
Traceback (most recent call last):
  File "scripts/resample.py", line 4, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_python.so: undefined symbol: PyObject_GET_WEAKREFS_LISTPTR

**Comment by Plachtaa** [comment]
刚才测试了一遍，STEP3应该是可以正常transcribe的，如果在import的时候报错的话建议重置会话
STEP1的pip报错不会影响运行

**Comment by T-huangzm** [comment]
> 刚才测试了一遍，STEP3应该是可以正常transcribe的，如果在import的时候报错的话建议重置会话 STEP1的pip报错不会影响
咋重置会话，刷新一下网页吗

**Comment by T-huangzm** [comment]
> 刚才测试了一遍，STEP3应该是可以正常transcribe的，如果在import的时候报错的话建议重置会话 STEP1的pip报错不会影响运行

重置会话是刷新网页吗

**Comment by urcanvm** [comment]
我也遇到了，请问解决了吗
