### ISSUE TITLE
[Bug]使用kaggle时STEP 4报错无final_annotation_train.txt

### ISSUE THREAD

**Issue by misaka10843** [Plachtaa/VITS-fast-fine-tuning#23]
在进行STEP 3时已经完成后似乎并没有生成任何txt
```
Detected language: ja
ですが……
Detected language: ja
キュッ!
Detected language: ja
絶好の探検日よりですね!
Detected language: ja
天文班の皆さんのように、私も大きな夢を持ちたいです!
Detected language: ja
見てください!あんなところに昔川だった痕跡が!
Detected language: ja
昔はこうやって測量しながら地図を作っていたみたいですね。私も自分の地図を作るために、少しずつ歩いていかないと。仙里の道も一歩から、ですね。
Detected language: ja
このあたりの測量はバッチリです!
Detected language: ja
こうです!
Detected language: ja
本当に今日バーベキューをやるんですか?
Downloading: "https://github.com/r9y9/open_jtalk/releases/download/v1.11.1/open_jtalk_dic_utf_8-1.11.tar.gz"
dic.tar.gz: 100%|██████████████████████████| 22.6M/22.6M [00:02<00:00, 10.1MB/s]
Extracting tar file /opt/conda/lib/python3.7/site-packages/pyopenjtalk/dic.tar.gz
finished
```

但是`ls ./`时并未有根目录更新文件

**之前**
```
LICENSE			   download_model.py	   sampled_audio4ft
README.md		   finetune_speaker.py	   sampled_audio4ft.txt
README_EN.md		   losses.py		   sampled_audio4ft.zip
README_ZH.md		   mel_processing.py	   text
VC_inference.py		   models.py		   transforms.py
attentions.py		   models_infer.py	   user_voice
commons.py		   modules.py		   user_voice_collect.py
configs			   monotonic_align	   utils.py
custom_character_anno.txt  preprocess.py	   video_transcribe.py
custom_character_voice	   pretrained_models	   voice_upload.py
data_utils.py		   requirements.txt	   whisper_transcribe.py
demucs_denoise.py	   requirements_infer.txt
```

**之后**
```
LICENSE			   demucs_denoise.py	   sampled_audio4ft
OUTPUT_MODEL		   download_model.py	   sampled_audio4ft.txt
README.md		   finetune_speaker.py	   sampled_audio4ft.zip
README_EN.md		   losses.py		   text
README_ZH.md		   mel_processing.py	   transforms.py
VC_inference.py		   models.py		   user_voice
__pycache__		   models_infer.py	   user_voice_collect.py
attentions.py		   modules.py		   utils.py
commons.py		   monotonic_align	   video_transcribe.py
configs			   preprocess.py	   voice_upload.py
custom_character_anno.txt  pretrained_models	   whisper_transcribe.py
custom_character_voice	   requirements.txt
data_utils.py		   requirements_infer.txt
```

导致STEP 4无法找到final_annotation_train.txt

```
Traceback (most recent call last):
  File "finetune_speaker.py", line 320, in <module>
    main()
  File "finetune_speaker.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/kaggle/working/VITS_voice_conversion/finetune_speaker.py", line 72, in run
    train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps.data)
  File "/kaggle/working/VITS_voice_conversion/data_utils.py", line 164, in __init__
    self.audiopaths_sid_text = load_filepaths_and_text(audiopaths_sid_text)
  File "/kaggle/working/VITS_voice_conversion/utils.py", line 144, in load_filepaths_and_text
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'final_annotation_train.txt'
```

但是因为看见 #14 中的问题，所以将colab运行完成的STEP 3中生成的`custom_character_anno.txt`下载下来上传到根目录，但是也不行

**custom_character_anno.txt大概内容**
```
./custom_character_voice/mai/processed_0.wav|1000|ga↑sʃɯ*kɯmi↓taina mo↑no↓desɯ*ka?
./custom_character_voice/mai/processed_1.wav|1000|a↑ɾi↓gatoo go↑zaima↓sɯ*!
```

请问如何才能生成final_annotation_train.txt？（或者final_annotation_train.txt是在哪里？）

[kaggle笔记本链接](https://www.kaggle.com/code/misaka10843/notebook545e2dc4e5)

**Comment by Plachtaa** [comment]
`final_annotation_train.txt`是通过`preprocess.py`生成的，你可以把它的源码单独拿出来debug一下，看看是哪一行报错了导致后面没能执行下去

**Comment by misaka10843** [comment]
原来如此
因为kaggle不支持tensorboard，所以我就直接将笔记本中的
```
%run preprocess.py
%reload_ext tensorboard
%tensorboard --logdir "./OUTPUT_MODEL"
```
这三行直接删除了，所以就并没有运行preprocess.py🤣
