### ISSUE TITLE
训练的时候好像没有读取数据？

### ISSUE THREAD

**Issue by fanyhchn** [Plachtaa/VITS-fast-fine-tuning#255]
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 1, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'caozong': 0}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 100, 'drop_speaker_embed': True}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
########################
final_annotation_train.txt
<data_utils.TextAudioSpeakerLoader object at 0x7f6263911340>
Bucket warning  
INFO:OUTPUT_MODEL:Loaded checkpoint './pretrained_models/G_0.pth' (iteration None)
INFO:OUTPUT_MODEL:Loaded checkpoint './pretrained_models/D_0.pth' (iteration None)
0it [00:10, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 1
/media/fan/b2454117-36b1-4bb9-b845-2f29702812d7/fan/miniconda3/envs/sovits/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
0it [00:04, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 2
0it [00:03, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 3
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 4
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 5
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 6
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 7
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 8
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 9
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 10
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 11
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 12
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 13
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 14
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 15
0it [00:01, ?it/s]
INFO:OUTPUT_MODEL:====> Epoch: 16
0it [00:01, ?it/s]
这是什么原因啊

**Comment by lqy9715** [comment]
请问您解决了吗？遇到和您相同的问题

**Comment by ControlNet** [comment]
同样遇到这个问题了。似乎是因为在`finetune_speaker_v2.py`中使用`DistributedBucketSampler`，而这个会drop掉超出bucket范围的音频，如果音频全部太长或者太短，就会被过滤掉。

```python
train_sampler = DistributedBucketSampler(
    train_dataset,
    hps.train.batch_size,
    [32,300,400,500,600,700,800,900,1000],  # >1000 or <32 will be dropped
    num_replicas=n_gpus,
    rank=rank,
    shuffle=True)
```

但是简单修改这个bucket的长度也会报错，不知道有没有什么好办法 。
```
Traceback (most recent call last):
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/main/GitRepos/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 153, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/home/main/GitRepos/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 173, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/home/main/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/main/GitRepos/VITS-fast-fine-tuning/data_utils.py", line 156, in __call__
    spec_padded[i, :, :spec.size(1)] = spec
RuntimeError: expand(torch.FloatTensor{[2, 513, 763]}, size=[2, 513]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
```

**Comment by Xuan2-33** [comment]
请问这个问题解决了吗

**Comment by HuaHuaY** [comment]
> 同样遇到这个问题了。似乎是因为在`finetune_speaker_v2.py`中使用`DistributedBucketSampler`，而这个会drop掉超出bucket范围的音频，如果音频全部太长或者太短，就会被过滤掉。
> 
> ```python
> train_sampler = DistributedBucketSampler(
>     train_dataset,
>     hps.train.batch_size,
>     [32,300,400,500,600,700,800,900,1000],  # >1000 or <32 will be dropped
>     num_replicas=n_gpus,
>     rank=rank,
>     shuffle=True)
> ```
> 
> 但是简单修改这个bucket的长度也会报错，不知道有没有什么好办法 。
> 
> ```
> Traceback (most recent call last):
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/home/main/GitRepos/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 153, in run
>     train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
>   File "/home/main/GitRepos/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 173, in train_and_evaluate
>     for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
>   File "/home/main/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
>     for obj in iterable:
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
>     data = self._next_data()
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
>     return self._process_data(data)
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
>     data.reraise()
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
>     raise exception
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/main/anaconda3/envs/vits/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
>     return self.collate_fn(data)
>   File "/home/main/GitRepos/VITS-fast-fine-tuning/data_utils.py", line 156, in __call__
>     spec_padded[i, :, :spec.size(1)] = spec
> RuntimeError: expand(torch.FloatTensor{[2, 513, 763]}, size=[2, 513]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
> ```

https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/51#issuecomment-1453830386
我遇到这个问题情况是和这个评论一样，数据里混了双通道音频。scripts/denoise_audio.py有一行会把双通道音频合成单通道，我用uvr替换demucs提取人声，这行代码没注意到忘记转单通道了。
```python
    # merge two channels into one
    wav = wav.mean(dim=0).unsqueeze(0)
```
