### ISSUE TITLE
加载vits 模型，使用interfere.exe 出现 size mismatch

### ISSUE THREAD

**Issue by qraccess** [Plachtaa/VITS-fast-fine-tuning#259]
Traceback (most recent call last):
  File "inference.py", line 97, in <module>
  File "utils.py", line 45, in load_checkpoint
  File "torch\nn\modules\module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([50, 192]).
[9920] Failed to execute script 'inference' due to unhandled exception!

模型来自极客团队训练的派蒙： https://github.com/zixiiu/Digital_Life_Server

**Comment by yihuitang** [comment]
我也遇到过类似的问题

**Comment by qraccess** [comment]
有谁知道这个怎么解决？

**Comment by BigMouseNie** [comment]
解决了吗

**Comment by BigMouseNie** [comment]
应该是config文件的问题，估计你不是自己训练的

**Comment by JunhaoHuang0615** [comment]
这个是因为config文件没有给正确，config文件中的symbol数量与模型不匹配，也许需要找他们更新一下config文件？

**Comment by WellTung666** [comment]
自己训练了模型放到数字生命项目中遇到同样的问题，请问如何解决的？谢谢~

**Comment by WellTung666** [comment]
> 这个是因为config文件没有给正确，config文件中的symbol数量与模型不匹配，也许需要找他们更新一下config文件？

请问自己训练的模型需要怎样修改呢？

**Comment by mikeyang01** [comment]
+1
