### ISSUE TITLE
步骤4报错

### ISSUE THREAD

**Issue by TerryYoung518** [Plachtaa/VITS-fast-fine-tuning#27]
内容为约1500条mp3格式短语音。
未勾选加入辅助训练数据。

错误信息如下：
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 133, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 153, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 988, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 598, in __init__
    self._sampler_iter = iter(self._index_sampler)
  File "/content/VITS-fast-fine-tuning/data_utils.py", line 233, in __iter__
    ids_bucket = ids_bucket + ids_bucket * (rem // len_bucket) + ids_bucket[:(rem % len_bucket)]
ZeroDivisionError: integer division or modulo by zero
```

**Comment by Plachtaa** [comment]
VITS内置采样器的问题，你的样本有几个speaker？

**Comment by TerryYoung518** [comment]
仅有1个speaker。
控制变量勾选”加入辅助训练数据“后未报错。

**Comment by Plachtaa** [comment]
之前我做实验的时候也碰到过这种情况，如果说话人只有1个，那么采样器就会抽风。
建议随便加几个说话人来防止它报错，或者勾选加入辅助训练数据。

**Comment by Plachtaa** [comment]
Close this issue due to long time of no reply
