### ISSUE TITLE
自动跳过训练步骤

### ISSUE THREAD

**Issue by OneTrueSum95** [Plachtaa/VITS-fast-fine-tuning#270]
开始训练后Epoch飞快的涨，但是模型没有正常训练

```
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 1 to ././OUTPUT_MODEL/G_0.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 1 to ././OUTPUT_MODEL/G_latest.pth
100% 1/1 [00:21<00:00, 21.13s/it]
INFO:OUTPUT_MODEL:====> Epoch: 1
/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py:138: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
  0% 0/1 [00:00<?, ?it/s]INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
100% 1/1 [00:10<00:00, 10.14s/it]
INFO:OUTPUT_MODEL:====> Epoch: 2
100% 1/1 [00:08<00:00,  8.35s/it]
INFO:OUTPUT_MODEL:====> Epoch: 3
100% 1/1 [00:07<00:00,  7.27s/it]
INFO:OUTPUT_MODEL:====> Epoch: 4
100% 1/1 [00:10<00:00, 10.56s/it]
INFO:OUTPUT_MODEL:====> Epoch: 1
/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py:138: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
  0% 0/1 [00:00<?, ?it/s]INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
100% 1/1 [00:10<00:00, 10.14s/it]
INFO:OUTPUT_MODEL:====> Epoch: 2
100% 1/1 [00:08<00:00,  8.35s/it]
INFO:OUTPUT_MODEL:====> Epoch: 3
100% 1/1 [00:07<00:00,  7.27s/it]
INFO:OUTPUT_MODEL:====> Epoch: 4
100% 1/1 [00:10<00:00, 10.56s/it]
INFO:OUTPUT_MODEL:====> Epoch: 5
100% 1/1 [00:07<00:00,  7.76s/it]
INFO:OUTPUT_MODEL:====> Epoch: 6
100% 1/1 [00:08<00:00,  8.17s/it]
INFO:OUTPUT_MODEL:====> Epoch: 7
100% 1/1 [00:10<00:00, 10.27s/it]
INFO:OUTPUT_MODEL:====> Epoch: 8
100% 1/1 [00:06<00:00,  6.90s/it]
INFO:OUTPUT_MODEL:====> Epoch: 9
100% 1/1 [00:09<00:00,  9.21s/it]
INFO:OUTPUT_MODEL:====> Epoch: 10
  0% 0/1 [00:00<?, ?it/s]INFO:OUTPUT_MODEL:Train Epoch: 11 [0%]
INFO:OUTPUT_MODEL:[3.131582021713257, 1.708096981048584, 0.016480620950460434, 0.5318384766578674, 3.3989124298095703, 3.8460075855255127, 10, 0.00019975014057813518]
100% 1/1 [00:12<00:00, 12.26s/it]
INFO:OUTPUT_MODEL:====> Epoch: 11
100% 1/1 [00:11<00:00, 11.26s/it]
INFO:OUTPUT_MODEL:====> Epoch: 12
100% 1/1 [00:09<00:00,  9.88s/it]
INFO:OUTPUT_MODEL:====> Epoch: 13
100% 1/1 [00:07<00:00,  7.22s/it]
INFO:OUTPUT_MODEL:====> Epoch: 14
.............
INFO:OUTPUT_MODEL:====> Epoch: 20
  0% 0/1 [00:00<?, ?it/s]INFO:OUTPUT_MODEL:Train Epoch: 21 [0%]
INFO:OUTPUT_MODEL:[3.006995916366577, 1.454353928565979, 0.025682387873530388, 1.106834053993225, 2.40323543548584, 0.13814112544059753, 20, 0.00019950059330492385]
Maximum epoch reached, closing training...
  0% 0/1 [00:10<?, ?it/s]
None
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 321, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
```
一轮只需要5秒，TensorBoard里也只有step 0的模型，上午还是正常的，不知道是哪里出了问题

**Comment by Plachtaa** [comment]
请检查`final_annotation_train.txt`是否为空，若为空则原因应该是音频数据上传格式有误导致没能读取到。

**Comment by OneTrueSum95** [comment]
谢谢，已解决

**Comment by Xuan2-33** [comment]
final_annotation_train.txt 里面有训练数据也会没有读取到任何训练内容怎么办呀

train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps.data, symbols)
上面的执行完成后train_dataset的长度是44

train_sampler = DistributedBucketSampler(
        train_dataset,
        hps.train.batch_size,
        [32, 300, 400, 500, 600, 700, 800, 900, 1000],
        num_replicas=n_gpus,
        rank=rank,
        shuffle=True)
上面的执行完成后train_sampler的长度是0，是上传的音频有问题吗，但是用这些音频训练其他TTS模型是没问题的

下面是final_annotation_train.txt前几行的数据
./custom_character_voice/a2/processed_0.wav|0|niɑʊ↓↑niɑʊ↓↑ t⁼ə tʰa→ ts`ʰweɪ→ wo↓↑ t⁼ɑʊ↓ ts`ʰən↑sɹ↓↑ t⁼ə iɛ↓p⁼ɑŋ→ wo↓↑uɑŋ↓ an→tʃ⁼iŋ↓ t⁼ə liŋ↑xwən↑ mən ts⁼aɪ↓.
./custom_character_voice/a2/processed_1.wav|0|i→. ʃiɑŋ→k⁼ɑŋ↓↑ t⁼ə kʰɑŋ↓ɹ`ɹ`↓tʃ⁼joʊ↓uɑŋ↑ɥn↓t⁼ʊŋ↓ i↓↑ tʃ⁼joʊ↓uɑŋ↑ wən↑xwa↓ ɥn↓t⁼ʊŋ↓ weɪ↓ ts`⁼u↓↑iɑʊ↓ ʃiŋ↑s`ɹ`↓.
./custom_character_voice/a2/processed_2.wav|0|tʃʰiŋ→tsʰɑʊ↓↑ joʊ↓ sʊŋ→ joʊ↓ ɹ`wan↓↑ waɪ→waɪ→ tʃʰɥ→tʃʰɥ→ t⁼ə ts`⁼weɪ→sweɪ↑ts`⁼ə t⁼ɑʊ↓lu↓ ʃiɑŋ↓ ɥæn↓↑ts`ʰu↓ jɛn↑s`ən→.
./custom_character_voice/a2/processed_3.wav|0|t⁼oʊ↓fu↓↑nɑʊ↓↑ pʰin↓↑ts`ʰɑŋ↑ k⁼wo↓ lə na↓ fɑŋ→fɑŋ→ts`⁼əŋ↓ts`⁼əŋ↓ p⁼aɪ↑p⁼aɪ↑ nən↓nən↓t⁼ə t⁼oʊ↓fu↓↑kʰwaɪ↓ ts`ʰɹ`→ k⁼wo↓xoʊ↓ man↓↑kʰoʊ↓↑ ɥ↑ʃiɑŋ→.

**Comment by kaidachen** [comment]
我也遇到相同的问题，请问是怎么解决的呢。训练数据是正常的，final_annotation_train.txt不为空。
--add_auxiliary_data True就不会出现这样的问题，但是，加辅助数据之后，训练出的音色全是辅助数据的音色。
