### ISSUE TITLE
所有epoch执行完毕后，抛出torch.multiprocessing.spawn.ProcessExitedException

### ISSUE THREAD

**Issue by Hyponarch** [Plachtaa/VITS-fast-fine-tuning#284]
每次微调的训练完成后，都会抛出这个异常，
环境是Centos8/Rocky8，2 * A100
```shell
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 351, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/.conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/.conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/.conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
``` 
请问要怎么解决？

**Comment by ice-lynn** [comment]
我刚开始训练，加载完模型就报这个错，是什么原因

**Comment by amazingchow** [comment]
if epoch > hps.max_epochs: 下面的exit() 改为 exit(code=0)可以解决
