### ISSUE TITLE
Step 3出错

### ISSUE THREAD

**Issue by HandsomeWu007** [Plachtaa/VITS-fast-fine-tuning#290]
在windows 本地标注长音频时出错

F:\Download\VITS-fast-fine-tuning-main>python scripts/long_audio_transcribe.py --languages "{CJ}" --whisper_size large
transcribing ./denoised_audio/Q_1.wav...

Traceback (most recent call last):
  File "scripts/long_audio_transcribe.py", line 41, in <module>
    result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
  File "F:\Program files\Python\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "F:\Program files\Python\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram
    audio = load_audio(audio)
  File "F:\Program files\Python\lib\site-packages\whisper\audio.py", line 46, in load_audio
    ffmpeg.input(file, threads=0)
  File "F:\Program files\Python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "F:\Program files\Python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "F:\Program files\Python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "F:\Program files\Python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Plachtaa** [comment]
请在根目录下尝试运行以下脚本：
```
import os
print(os.path.exists("./denoised_audio/Q_1.wav"))
```
若返回为`False`，说明该文件不存在或路径配置有误
若返回为`True`，需要进一步探讨

**Comment by HandsomeWu007** [comment]
结果是true

**Comment by HandsomeWu007** [comment]
所以是什么情况呢？

**Comment by Plachtaa** [comment]
问题可能出在ffmpeg上
请尝试在Windows cmd中运行：
`ffmpeg -version`
如果该指令没能正确返回信息，则请检查ffmpeg是否正确按照并且添加到环境变量中

**Comment by HandsomeWu007** [comment]
谢谢大佬，在我把ffmpeg添加到环境变量中后，又通过pip3装了ffmpeg python就可以运行了。麻烦你了

**Comment by ak8893893** [comment]
感謝 @Plachtaa  安裝好ffmpeg並添加到環境變數成功解決了這個問題  太感謝了!

我是參考這篇安裝ffmpeg的
https://vocus.cc/article/64701a2cfd897800014daed0
