### ISSUE TITLE
在推理时显示finetune_speaker.json不存在

### ISSUE THREAD

**Issue by HandsomeWu007** [Plachtaa/VITS-fast-fine-tuning#296]
Traceback (most recent call last):
  File "VC_inference.py", line 93, in <module>
    hps = utils.get_hparams_from_file(args.config_dir)
  File "F:\Download\VITS-fast-fine-tuning-main\utils.py", line 362, in get_hparams_from_file
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './finetune_speaker.json'

**Comment by Plachtaa** [comment]
改json的文件名

**Comment by HandsomeWu007** [comment]
指改哪一个

**Comment by Plachtaa** [comment]
配置文件名字改成`finetune_speaker.json`

**Comment by Plachtaa** [comment]
要放到根目录下

**Comment by HandsomeWu007** [comment]
emm 放完了 但现在又显示下面这个

Traceback (most recent call last):
  File "VC_inference.py", line 106, in <module>
    speakers = list(hps.speakers.keys())
AttributeError: 'list' object has no attribute 'keys'

**Comment by Plachtaa** [comment]
你从哪下的config，如果是训练脚本生成的config则会使用`dict`存放speaker信息，这个报错说明你的config使用`list`存放的

**Comment by HandsomeWu007** [comment]
嘶 没事了 copy时选错到了另外一个config。麻烦了

**Comment by qiuyuzhao** [comment]
> 你从哪下的config，如果是训练脚本生成的config则会使用`dict`存放speaker信息，这个报错说明你的config使用`list`存放的
您好：
https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/VITS-Chinese/config.json,  这个链接提供的config里面就是list存放的，脚本里那个是生成训练config的？
