### ISSUE TITLE
本地训练，运行python finetune_speaker_v2.py -m G:/Work-base/Colab-WorkBase/VITS-fast-fine-tuning/Output-L1 --max_epochs "100000" --drop_speaker_embed True报错

### ISSUE THREAD

**Issue by SunJR24** [Plachtaa/VITS-fast-fine-tuning#305]
本地训练，运行python finetune_speaker_v2.py -m G:/Work-base/Colab-WorkBase/VITS-fast-fine-tuning/Output-L1 --max_epochs "100000" --drop_speaker_embed True报错

根据错误信息显示，问题出在 mel_processing.py 文件中的 mel() 函数上。它似乎被定义为不接受任何位置参数，但是调用时却传入了五个参数：sampling_rate、n_fft、num_mels、fmin 和 fmax。

源码位置mel_spectrogram_torch() 函数时需要传递的参数与函数定义中的参数数量和顺序一致。根据函数定义，该函数期望接收以下参数：y、n_fft、num_mels、sampling_rate、hop_size、win_size、fmin、fmax 和 center。

报错信息
(T3) PS G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning> python finetune_speaker_v2.py -m G:/Work-base/Colab-WorkBase/VITS-fast-fine-tuning/Output-L1 --max_epochs "100000" --drop_speaker_embed True
--- Logging error ---
Traceback (most recent call last):
  File "G:\Anaconda3\envs\T3\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\u0283' in position 1409: illegal multibyte sequence
Call stack:
  File "<string>", line 1, in <module>
  File "G:\Anaconda3\envs\T3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "G:\Anaconda3\envs\T3\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "G:\Anaconda3\envs\T3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "G:\Anaconda3\envs\T3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Anaconda3\envs\T3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 63, in run
    logger.info(hps)
Message: {'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 3, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'VO_nahida': 0, 'specialweek': 1, 'zhongli': 2}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': 'G:/Work-base/Colab-WorkBase/VITS-fast-fine-tuning/Output-L1', 'max_epochs': 100000, 'cont': False, 'drop_speaker_embed': True, 'train_with_pretrained_model': True, 'preserved': 4}
Arguments: ()
INFO:Output-L1:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 3, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'VO_nahida': 0, 'specialweek': 1, 'zhongli': 2}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': 'G:/Work-base/Colab-WorkBase/VITS-fast-fine-tuning/Output-L1', 'max_epochs': 100000, 'cont': False, 'drop_speaker_embed': True, 'train_with_pretrained_model': True, 'preserved': 4}
WARNING:Output-L1:G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Train with pretrained model...
INFO:Output-L1:emb_g.weight is not in the checkpoint
INFO:Output-L1:Loaded checkpoint './pretrained_models/G_0.pth' (iteration None)
INFO:Output-L1:Loaded checkpoint './pretrained_models/D_0.pth' (iteration None)
  0%|                                                                                           | 0/63 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 351, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "G:\Anaconda3\envs\T3\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "G:\Anaconda3\envs\T3\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "G:\Anaconda3\envs\T3\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "G:\Anaconda3\envs\T3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 154, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 184, in train_and_evaluate
    mel = spec_to_mel_torch(
  File "G:\Work-base\Colab-WorkBase\VITS-fast-fine-tuning\mel_processing.py", line 78, in spec_to_mel_torch
    mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
TypeError: mel() takes 0 positional arguments but 5 were given

**Comment by SunJR24** [comment]
问题解决了   librosa需要0.9.2版  不能升级

**Comment by swimchicken** [comment]
> 问题解决了 librosa需要0.9.2版 不能升级

你好,不好意思方便
請教一下只要升級librosa0.9.2版就好嗎?主要是我確定是0.9.2版.但運行結果後與你當時錯誤一模一樣.
![螢幕擷取畫面 2023-07-03 143412](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/92098221/0783aa1f-3886-4d38-84bb-856dd01d64d0)

**Comment by SunJR24** [comment]
确定是0.9.2就行   你可以卸了重新装下试试

**Comment by zicheqingluo** [comment]
不是这个问题，亲测无效

**Comment by swimchicken** [comment]
確實不是這個問題,只是我上上個月好像處理好了,有需要的話我可以幫忙debug.

**Comment by mikeyang01** [comment]
pip install librosa==0.9.2

**Comment by Json0926** [comment]
大佬的json做了什么修改的，symbols和默认的不一样
