### ISSUE TITLE
3.5步时出现错误，更换了多个运行时,均会在此处抛出同样的错误

### ISSUE THREAD

**Issue by 1634222787** [Plachtaa/VITS-fast-fine-tuning#320]
Traceback (most recent call last):
  File "preprocess_v2.py", line 79, in <module>
    import text
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/text/__init__.py", line 2, in <module>
    from text import cleaners
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/text/cleaners.py", line 6, in <module>
    from text.english import english_to_lazy_ipa, english_to_ipa2, english_to_lazy_ipa2
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/text/english.py", line 20, in <module>
    import inflect
  File "/usr/local/lib/python3.8/dist-packages/inflect/__init__.py", line 77, in <module>
    from pydantic.typing import Annotated
ImportError: cannot import name 'Annotated' from 'pydantic.typing' (/usr/local/lib/python3.8/dist-packages/pydantic/typing.py)

**Comment by 1634222787** [comment]
此处存在文件夹嵌套，是我重新尝试运行第1步安装依赖后出现的，可以忽略

**Comment by ADT109119** [comment]
可能是因為最近 pydantic 出了 2.0 版本
試試將版本降回1.10.4
以下是指令
```
!python3.8 -m pip uninstall pydantic
!python3.8 -m pip install pydantic==1.10.4
```
我自己測試這樣就可以解決
希望對你有幫助

**Comment by caoshuisi** [comment]
我也刚好试了2次都是这个报错，恰好看到了这个提问，请问这个指令是加到3.5步的吗？

**Comment by ADT109119** [comment]
直接創一個新的程式碼區塊
貼上後執行

**Comment by ADT109119** [comment]
> 我也刚好试了2次都是这个报错，恰好看到了这个提问，请问这个指令是加到3.5步的吗？

直接創一個新的程式碼區塊
貼上後執行

**Comment by caoshuisi** [comment]
> > 我也刚好试了2次都是这个报错，恰好看到了这个提问，请问这个指令是加到3.5步的吗？
> 
> 直接創一個新的程式碼區塊 貼上後執行

谢谢大佬

**Comment by mikamijpen** [comment]
建议作者改一下，都有这个问题了

**Comment by Plachtaa** [comment]
感谢提醒，已修改colab notebook

**Comment by cqfxchina** [comment]
use  pydantic 1.10.13  fixed.
