### ISSUE TITLE
自动处理出错了，昨天都没问题的

### ISSUE THREAD

**Issue by LuanSAD** [Plachtaa/VITS-fast-fine-tuning#337]
Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 3, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
Traceback (most recent call last):
  File "scripts/long_audio_transcribe.py", line 2, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
Traceback (most recent call last):
  File "scripts/short_audio_transcribe.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
Traceback (most recent call last):
  File "scripts/resample.py", line 4, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

昨天都没问题的，怎么解决啊

**Comment by LinChihShan** [comment]
哥們, 我也遇到同樣問題, 我猜是po主在維護中的關係(首頁read me中有提到).

**Comment by Lemondogdog** [comment]
就是昨天开始维护。可能是有关系吧，我也是试了几次卡在  STEP 3 自动处理所有上传的数据  这边 它不会进行自动识别文本标注了。

**Comment by anfogy** [comment]
请参考这个issue: [#62470](https://github.com/pytorch/pytorch/issues/62470)

**Comment by anfogy** [comment]
看起来你并没有whisper库，请重跑step 1(记得删除运行时或%cd /content/)

**Comment by LuanSAD** [comment]
已恢复正常。

**Comment by 2579356425** [comment]
@LuanSAD 你好，请问怎么解决的这个问题。我安装了whisper库，但是前面ImportError没有解决。如果是使用$ python setup.py develop && python -c "import torch"，应该在哪个路径下执行？

**Comment by anfogy** [comment]
> @LuanSAD 你好，请问怎么解决的这个问题。我安装了whisper库，但是前面ImportError没有解决。如果是使用$ python setup.py develop && python -c "import torch"，应该在哪个路径下执行？

是numpy版本问题，在step 1加入更新numpy，请参考[#62470中白开水的解决方案](https://github.com/pytorch/pytorch/issues/62470#issuecomment-1062857229)
