### ISSUE TITLE
colab和本地的STEP3.5出现同样新问题

### ISSUE THREAD

**Issue by ASAGAO123** [Plachtaa/VITS-fast-fine-tuning#342]
昨天晚间运行正常，但是今天早晨开始step3.5报错。报错内容如下：
Traceback (most recent call last): File "preprocess_v2.py", line 131, in <module> import text File "/content/VITS-fast-fine-tuning/text/__init__.py", line 2, in <module> from text import cleaners File "/content/VITS-fast-fine-tuning/text/cleaners.py", line 2, in <module> from text.japanese import japanese_to_romaji_with_accent, japanese_to_ipa, japanese_to_ipa2, japanese_to_ipa3 File "/content/VITS-fast-fine-tuning/text/japanese.py", line 2, in <module> from unidecode import unidecode ModuleNotFoundError: No module named 'unidecode'

**Comment by tian1326** [comment]
检查第一步的输出是否有像https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/343 中一样的报错，如果有试着按其中的方法修复，没有可以尝试安装unidecode，新建一个代码块输入一下内容 ```!python3.8 -m pip install unidecode```再点击执行

**Comment by ASAGAO123** [comment]
> 检查第一步的输出是否有像#343 中一样的报错，如果有试着按其中的方法修复，没有可以尝试安装unidecode，新建一个代码块输入一下内容 `!python3.8 -m pip install unidecode`再点击执行

大佬，确实第一部出现了#343中的报错，我按照你在那一楼的回复在本地试了一下。
如果直接采用'pip install --no-build-isolation -r requirements.txt',会出现如下报错：
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
所以我尝试了直接使用'pip install pyopenjtalk --no-build-isolation'，但这样话在运行3.5步的时候就会获得和#338一样的报错：
Traceback (most recent call last):
  File "preprocess_v2.py", line 131, in <module>
    import text
  File "D:\Project\VITS-fast-fine-tuning-chinese\text\__init__.py", line 2, in <module>
    from text import cleaners
  File "D:\Project\VITS-fast-fine-tuning-chinese\text\cleaners.py", line 2, in <module>
    from text.japanese import japanese_to_romaji_with_accent, japanese_to_ipa, japanese_to_ipa2, japanese_to_ipa3
  File "D:\Project\VITS-fast-fine-tuning-chinese\text\japanese.py", line 3, in <module>
    import pyopenjtalk
  File "D:\conda\vits-fft-chinese\lib\site-packages\pyopenjtalk\__init__.py", line 10, in <module>
    from pyopenjtalk.htsengine import HTSEngine
  File "pyopenjtalk\htsengine.pyx", line 1, in init pyopenjtalk.htsengine
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
等下我试一下colab里面的情况，说不定是我本地的环境配置有问题。

**Comment by ASAGAO123** [comment]
> > > 检查第一步的输出是否有像#343 中一样的报错，如果有试着按其中的方法修复，没有可以尝试安装unidecode，新建一个代码块输入一下内容 `!python3.8 -m pip install unidecode`再点击执行
> > 
> > 
> > 大佬，确实第一部出现了#343中的报错，我按照你在那一楼的回复在本地试了一下。 如果直接采用'pip install --no-build-isolation -r requirements.txt',会出现如下报错： Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> > × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [15 lines of output] 所以我尝试了直接使用'pip install pyopenjtalk --no-build-isolation'，但这样话在运行3.5步的时候就会获得和#338一样的报错： Traceback (most recent call last): File "preprocess_v2.py", line 131, in import text File "D:\Project\VITS-fast-fine-tuning-chinese\text__init__.py", line 2, in from text import cleaners File "D:\Project\VITS-fast-fine-tuning-chinese\text\cleaners.py", line 2, in from text.japanese import japanese_to_romaji_with_accent, japanese_to_ipa, japanese_to_ipa2, japanese_to_ipa3 File "D:\Project\VITS-fast-fine-tuning-chinese\text\japanese.py", line 3, in import pyopenjtalk File "D:\conda\vits-fft-chinese\lib\site-packages\pyopenjtalk__init__.py", line 10, in from pyopenjtalk.htsengine import HTSEngine File "pyopenjtalk\htsengine.pyx", line 1, in init pyopenjtalk.htsengine ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject 等下我试一下colab里面的情况，说不定是我本地的环境配置有问题。
> 
> 抱歉我没有测试完就发解决方案了，现在已经更新，重新看一下那里的回复

感谢大佬！！！

**Comment by anfogy** [comment]
昨天被这玩意折磨了10小时，太痛苦了，该死的cython 3.0

**Comment by uuKhost** [comment]
> > 检查第一步的输出是否有像#343 中一样的报错，如果有试着按其中的方法修复，没有可以尝试安装unidecode，新建一个代码块输入一下内容 `!python3.8 -m pip install unidecode`再点击执行
> 
> 那第一步没有报错，所有依赖成功安装的情况下依然出现No module named 'unidecode'的报错怎么办呢，也试过换其他版本的unidecode和更新pyopenjtalk，但还是同样的报错

打扰了，原来colab端不需要使用3.8版本的python吗，我怀疑是插件代码结构的问题所以今天改回3.10版本的python试了试，没想到可以了
