### ISSUE TITLE
Colab Step 1 Error (ModuleNotFoundError: No module named 'distutils.cmd')

### ISSUE THREAD

**Issue by HWcomss** [Plachtaa/VITS-fast-fine-tuning#350]
In Colab, I followed this solution #343  
but still have a issue, `Error (ModuleNotFoundError: No module named 'distutils.cmd')`  
so i Added this line:  
`!sudo apt-get install python3-distutils`

and then, for some reason I get same error again  
[ERROR: Could not build wheels for pyopenjtalk, which is required to install pyproject.toml-based projects](https://github.com/r9y9/pyopenjtalk/issues/48)  

so i just installed pyopenjtalk again manually with
`!pip install pyopenjtalk --no-build-isolation`

final code is here:
```
#@title STEP 1 复制代码库并安装运行环境
#@markdown #STEP 1 (6 min)
#@markdown ##复制代码库并安装运行环境
#@markdown ##Clone repository & Build environment
!apt-get install python3.8

!sudo apt-get install python3-distutils # ADDED

!cp -r /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.8/
!git clone https://github.com/Plachtaa/VITS-fast-fine-tuning.git

!python3.8 -m pip install --upgrade --force-reinstall regex
!python3.8 -m pip install --upgrade --force-reinstall numba
!python3.8 -m pip install --force-reinstall soundfile
!python3.8 -m pip install --force-reinstall gradio
!python3.8 -m pip install imageio==2.4.1
!python3.8 -m pip install --upgrade youtube-dl
!python3.8 -m pip install moviepy

!python3.8 -m pip install --no-build-isolation -r requirements.txt # ADDED
!python3.8 -m pip install pyopenjtalk --no-build-isolation # ADDED
!python3.8 -m pip install --upgrade numpy # ADDED
!python3.8 -m pip install --upgrade pyzmq

!python3.8 -m pip install pydantic==1.10.4
# !pip install -U openai-whisper

# build monotonic align
%cd monotonic_align/
!mkdir monotonic_align
!python3.8 setup.py build_ext --inplace
%cd ..
!mkdir pretrained_models
# download data for fine-tuning
!wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip
!unzip sampled_audio4ft_v2.zip

%cd VITS-fast-fine-tuning
# create necessary directories
!mkdir video_data
!mkdir raw_audio
!mkdir denoised_audio
!mkdir custom_character_voice
!mkdir segmented_character_voice
```

I didn't test other steps yet. but there's no error anymore in step 1

**Comment by HWcomss** [comment]
I faced same Issue #351, so I decide to install packages one by one.
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/88720310/e037cca4-8fef-4eb5-8f09-76e13ec1cf15)
I think there's also problem with installing `scipy==1.5.2` in requirements.txt


I just deleted scipy==1.5.2 from requirement using this line
```
with open('requirements.txt', "r") as file:
    _lines = file.readlines()
_lines = [line for line in _lines if not line.strip().startswith("scipy==1.5.2")]
with open('requirements.txt', "w") as file:
    file.writelines(_lines)
```
finally, I tried to install packages and there's no error I get
```
!python -m pip install --no-build-isolation -r requirements.txt
```


![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/88720310/5655e49b-27b7-49f0-8d5a-2da870ade1ad)

**Comment by anfogy** [comment]
Cool solutions!

**Comment by anfogy** [comment]
Actually, apt-get python3-distutils won't work, still getting the same issue. `!sudo apt-get install python3.8-distutils` worked for me. The 3.10 version of distutils is not usable for py3.8(In this project)

**Comment by HWcomss** [comment]
yeah, I still get same issue #351, now I'll test whole installation again with default python version of colab (3.10) using just `!pip install `

**Comment by anfogy** [comment]
No error in step 1 now, testing other steps now

**Comment by HWcomss** [comment]
I'm not exprienced with python. so I'm not sure but I believe it installed from requirement.txt
here's my full code of STEP 1
```
#@title STEP 1 复制代码库并安装运行环境
#@markdown #STEP 1 (6 min)
#@markdown ##复制代码库并安装运行环境
#@markdown ##Clone repository & Build environment

!git clone https://github.com/Plachtaa/VITS-fast-fine-tuning.git
!python -m pip install --upgrade --force-reinstall regex
!python -m pip install --upgrade --force-reinstall numba
!python -m pip install --force-reinstall soundfile
# !python3.8 -m pip install --force-reinstall gradio
# !python3.8 -m pip install imageio==2.4.1
# !python3.8 -m pip install --upgrade youtube-dl
# !python3.8 -m pip install moviepy
%cd VITS-fast-fine-tuning

with open('requirements.txt', "r") as file:
    _lines = file.readlines()
_lines = [line for line in _lines if not line.strip().startswith("scipy==1.5.2")]
with open('requirements.txt', "w") as file:
    file.writelines(_lines)

!python -m pip install --no-build-isolation -r requirements.txt
!python -m pip install --upgrade numpy

!python -m pip install --upgrade pyzmq
!python -m pip install pydantic==1.10.4
# build monotonic align
%cd monotonic_align/
!mkdir monotonic_align
!python setup.py build_ext --inplace
%cd ..
!mkdir pretrained_models
# download data for fine-tuning
!wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip
!unzip sampled_audio4ft_v2.zip
# create necessary directories
!mkdir video_data
!mkdir raw_audio
!mkdir denoised_audio
!mkdir custom_character_voice
!mkdir segmented_character_voice
```

**Comment by anfogy** [comment]
After using -verbose in pip install pyopenjtalk, I found that maybe it's the issue with C++ environment, sorry for I have to go out, you can try changing the C++ environment

`!python3.8 -m pip install pyopenjtalk -v`

**Comment by HWcomss** [comment]
also In STEP3, I successed to run `!python scripts/denoise_audio.py`
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/88720310/e0a7a4e8-3907-46bb-9335-8b836e0f4b7a)

but getting error from scripts/long_audio_transcribe.py
```
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 2, in <module>
    import whisper
  File "/usr/local/lib/python3.10/dist-packages/whisper/__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "/usr/local/lib/python3.10/dist-packages/whisper/model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 7, in <module>
    import numba
  File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/scripts/short_audio_transcribe.py", line 1, in <module>
    import whisper
  File "/usr/local/lib/python3.10/dist-packages/whisper/__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "/usr/local/lib/python3.10/dist-packages/whisper/model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 7, in <module>
    import numba
  File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/usr/local/lib/python3.10/dist-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less
```

**Comment by anfogy** [comment]
numpy version has an error with numba, you updated the numpy version, maybe you have to updated the numba version too. I think it may cause some problem with the original code in this project.

**Comment by HWcomss** [comment]
> numpy version has an error with numba, you updated the numpy version, maybe you have to updated the numba version too. I think it may cause some problem with the original code in this project.

I updated numba using original colab's code, but using `!python -m pip`
`!python -m pip install --upgrade --force-reinstall numba`

and here's i got
```
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
100%|█████████████████████████████████████| 2.87G/2.87G [00:43<00:00, 71.4MiB/s]
transcribing ./denoised_audio/test.wav...

ko not supported, ignoring...
Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
/usr/local/lib/python3.10/dist-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.
```
I think it's going to work, but my audio source was not long enough i guess (my audio source length is 6minutes 37seconds)
I'll try it with other audio source

**Comment by HWcomss** [comment]
> Actually, apt-get python3-distutils won't work, still getting the same issue. `!sudo apt-get install python3.8-distutils` worked for me. The 3.10 version of distutils is not usable for py3.8(In this project).
> 
> Installing scipy didn't print error out, dunno why.

I think In 3.10 Python, scipy 1.5.2 is not supported but In 3.8, works.
Anyways, I successed to transcribing in STEP 3 using 3.10 python (default colab python) but haven't tested further steps.
I'll share my edited [colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing)
I hope everyone works with this

**Comment by anfogy** [comment]
Haven't tested it yet, how about `preprocess_v2.py`, that's the most important one, if you can run it then it should be good with all the reset.

**Comment by HWcomss** [comment]
> numpy version has an error with numba, you updated the numpy version, maybe you have to updated the numba version too. I think it may cause some problem with the original code in this project.

I realized there's `numpy==1.21.6` in requirements'txt but upgraded it below with `!python -m pip install --upgrade numpy`
so I just removed upgrading line.

> Haven't tested it yet, how about `preprocess_v2.py`, that's the most important one, if you can run it then it should be good with all the reset.

I'll try extra steps if 1~3 steps are working correctly

**Comment by HWcomss** [comment]
1~3.5 steps works well.
but I got error instantly when trying to run step 4
```
ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2023-07-20 11:32:09.763322: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/main.py", line 39, in run_main
    main_lib.global_init()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/main_lib.py", line 40, in global_init
    if getattr(tf, "__version__", "stub") == "stub":
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/util/nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/dtypes.py", line 37, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 3, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'Rie': 0, 'specialweek': 1, 'zhongli': 2}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 200, 'cont': True, 'drop_speaker_embed': False, 'train_with_pretrained_model': True, 'preserved': 4}
2023-07-20 11:32:19.585229: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core._multiarray_umath failed to import
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 372, in <module>
    main()
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 65, in run
    writer = SummaryWriter(log_dir=hps.model_dir)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 247, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 277, in _get_file_writer
    self.file_writer = FileWriter(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 76, in __init__
    self.event_writer = EventFileWriter(
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/__init__.py", line 45, in tf
    import tensorflow
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python import data
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 22, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/util/structure.py", line 22, in <module>
    from tensorflow.python.data.util import nest
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/util/nest.py", line 34, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/sparse_tensor.py", line 25, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/constant_op.py", line 25, in <module>
    from tensorflow.python.eager import execute
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/dtypes.py", line 37, in <module>
    _np_bfloat16 = _pywrap_bfloat16.TF_bfloat16_type()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
```

**Comment by HWcomss** [comment]
before running STEP 4
I ran these lines:
```
!pip install --upgrade numpy
!pip install --upgrade numba
```
and I think it's working!
now I'm wating for training

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/88720310/c88ca46b-5e46-4efd-be1b-ef24c566fade)

**Comment by HWcomss** [comment]
unfortunately, I used all of gpu usage. also i don't know why but traning was too slow (spent 1 hours for 40epochs)
I'll try again tomorrow.

**Comment by WinterFellW** [comment]
> unfortunately, I used all of gpu usage. also i don't know why but traning was too slow (spent 1 hours for 40epochs) but I was able to listen preview audio from tensorboard and it seems program is working. ![image](https://user-images.githubusercontent.com/88720310/254903613-d66e162a-d8db-420f-b138-1ee7a57043f8.png)
> 
> I'll try again tomorrow.

did you clicked "add auxilary"?It's gonna be much slower if so

**Comment by HWcomss** [comment]
> > unfortunately, I used all of gpu usage. also i don't know why but traning was too slow (spent 1 hours for 40epochs) but I was able to listen preview audio from tensorboard and it seems program is working. ![image](https://user-images.githubusercontent.com/88720310/254903613-d66e162a-d8db-420f-b138-1ee7a57043f8.png)
> > I'll try again tomorrow.
> 
> did you clicked "add auxilary"?It's gonna be much slower if so

yes well, I'm going to uncheck it in other training  
thanks for the information  


@Plachtaa I also successed to run this [colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing)   
big thanks to you if you update the original colab with this solution

**Comment by WinterFellW** [comment]
> 

Well I think you're right.I canceled Add Auxiliary but it still goes slowly.So maybe there's something wrong.

**Comment by anfogy** [comment]
Thank you so much buddy, very appreciated for your great work!
