### ISSUE TITLE
STEP 3 自动处理数据报错

### ISSUE THREAD

**Issue by 2579356425** [Plachtaa/VITS-fast-fine-tuning#351]
Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 3, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
Traceback (most recent call last):
  File "scripts/long_audio_transcribe.py", line 5, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
Traceback (most recent call last):
  File "scripts/short_audio_transcribe.py", line 4, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.
Traceback (most recent call last):
  File "scripts/resample.py", line 4, in <module>
    import torchaudio
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_extension/__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import fail_with_message, is_module_available, no_op
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/_internal/__init__.py", line 1, in <module>
    from torch.hub import download_url_to_file, load_state_dict_from_url
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 443, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

这个怎么解决，setup.py文件在哪？

**Comment by anfogy** [comment]
请参考#343 与#337 中的解决方案，下次留issue记得自己翻翻哦~

**Comment by anfogy** [comment]
参见#350 ，在pip install之前加入`!sudo apt-get install python3-distutils`来解决

**Comment by WinterFellW** [comment]
> 参见#350 ，在pip install之前加入`!sudo apt-get install python3.8-distutils`来解决

又出问题了。。。
我按照这个加了之后 也按照之前说的替换了代码 但是还是有bug 似乎和替换代码前的一样
  error: subprocess-exited-with-error
  
  × Building wheel for pyopenjtalk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyopenjtalk (pyproject.toml) ... error
  ERROR: Failed building wheel for pyopenjtalk

这是step1代码部分
!apt-get install python3.8
!cp -r /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.8/
!git clone https://github.com/Plachtaa/VITS-fast-fine-tuning.git
!sudo apt-get install python3.8-distutils
!python3.8 -m pip install --upgrade --force-reinstall regex
!python3.8 -m pip install --upgrade --force-reinstall numba
!python3.8 -m pip install --force-reinstall soundfile
!python3.8 -m pip install --force-reinstall gradio
!python3.8 -m pip install imageio==2.4.1
!python3.8 -m pip install --upgrade youtube-dl
!python3.8 -m pip install moviepy
%cd VITS-fast-fine-tuning
!python3.8 -m pip install --no-build-isolation -r requirements.txt
!python3.8 -m pip install --upgrade numpy
!python3.8 -m pip install --upgrade pyzmq
!python3.8 -m pip install pydantic==1.10.4
# build monotonic align
%cd monotonic_align/
!mkdir monotonic_align
!python3.8 setup.py build_ext --inplace
%cd ..
!mkdir pretrained_models
# download data for fine-tuning
!wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip
!unzip sampled_audio4ft_v2.zip
# create necessary directories
!mkdir video_data
!mkdir raw_audio
!mkdir denoised_audio
!mkdir custom_character_voice
!mkdir segmented_character_voice

**Comment by HWcomss** [comment]
> > 参见#350 ，在pip install之前加入`!sudo apt-get install python3.8-distutils`来解决
> 
> 又出问题了。。。 我按照这个加了之后 也按照之前说的替换了代码 但是还是有bug 似乎和替换代码前的一样 error: subprocess-exited-with-error
> 
> × Building wheel for pyopenjtalk (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. Building wheel for pyopenjtalk (pyproject.toml) ... error ERROR: Failed building wheel for pyopenjtalk
> 
> 这是step1代码部分 !apt-get install python3.8 !cp -r /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.8/ !git clone https://github.com/Plachtaa/VITS-fast-fine-tuning.git !sudo apt-get install python3.8-distutils !python3.8 -m pip install --upgrade --force-reinstall regex !python3.8 -m pip install --upgrade --force-reinstall numba !python3.8 -m pip install --force-reinstall soundfile !python3.8 -m pip install --force-reinstall gradio !python3.8 -m pip install imageio==2.4.1 !python3.8 -m pip install --upgrade youtube-dl !python3.8 -m pip install moviepy %cd VITS-fast-fine-tuning !python3.8 -m pip install --no-build-isolation -r requirements.txt !python3.8 -m pip install --upgrade numpy !python3.8 -m pip install --upgrade pyzmq !python3.8 -m pip install pydantic==1.10.4
> 
> # build monotonic align
> %cd monotonic_align/ !mkdir monotonic_align !python3.8 setup.py build_ext --inplace %cd .. !mkdir pretrained_models
> 
> # download data for fine-tuning
> !wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip !unzip sampled_audio4ft_v2.zip
> 
> # create necessary directories
> !mkdir video_data !mkdir raw_audio !mkdir denoised_audio !mkdir custom_character_voice !mkdir segmented_character_voice

你能试试这个吗? [Colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing)

**Comment by WinterFellW** [comment]
> 

试过了 也不行

**Comment by HWcomss** [comment]
> > 
> 
> 试过了 也不行

第 1 步中有一个错误，我更新了它，现在我正在测试第 4 步，我相信这会起作用。 请再次尝试我的 [colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing) 链接，如果有错误请告诉我。- Sorry I'm using google translator

**Comment by WinterFellW** [comment]
> > > 
> > 
> > 
> > 试过了 也不行
> 
> 第 STEP 1 中有一个错误，我更新了它，现在我正在测试第 STEP 4，我相信这会起作用。 请再次尝试我的 [colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing) 链接，如果有错误请告诉我。- Sorry I'm using google translator

It works perfectly now
Thank you !!!

**Comment by 2579356425** [comment]
> > > 
> > 
> > 
> > 试过了 也不行
> 
> 第 STEP 1 中有一个错误，我更新了它，现在我正在测试第 STEP 4，我相信这会起作用。 请再次尝试我的 [colab](https://colab.research.google.com/drive/1SCxgL2EQX25i0MCqXY173Ekykvz9pKuE?usp=sharing) 链接，如果有错误请告诉我。- Sorry I'm using google translator

很感谢您分享的这个colab链接，昨天可以正常工作，但是今天我在运行STEP3.5的preprocess_v2.py时，报错No module named ruamel,解决方法是在STEP3.5之前安装此配置文件，代码如下：` !python -m pip install ruamel.yaml`

**Comment by Plachtaa** [comment]
colab现已修复，可以正常运行了

**Comment by anfogy** [comment]
> colab现已修复，可以正常运行了

Thanks for your works!
