### ISSUE TITLE
准备开始训练时提示ffmpeg没有安装，但我已经正确设置环境变量了

### ISSUE THREAD

**Issue by XGXG114514** [Plachtaa/VITS-fast-fine-tuning#363]
E:\Program Files (x86)\VITS-fast-fine-tuning>%PYTHON% finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs "800" --drop_speaker_embed True
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\__init__.py", line 67, in <module>
    _init_ffmpeg()
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\utils.py", line 87, in _init_ffmpeg
    raise ImportError("FFmpeg libraries are not found. Please install FFmpeg.") from err
ImportError: FFmpeg libraries are not found. Please install FFmpeg.
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\utils.py", line 85, in _init_ffmpeg
    _load_lib("libtorchaudio_ffmpeg")
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\Program Files (x86)\VITS-fast-fine-tuning\vits-fast-finetuning\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by anfogy** [comment]
重装torchaudio试试

**Comment by XGXG114514** [comment]
卸载重装了，但问题依旧存在（torchaudio-2.0.2），这会不会和ffmpeg版本有关系？之前安装6.0和现在的4.4都报错

**Comment by XGXG114514** [comment]
> 重装torchaudio试试
卸载重装了，但问题依旧存在（torchaudio-2.0.2），这会不会和ffmpeg版本有关系？之前安装6.0和现在的4.4都报错

**Comment by anfogy** [comment]
有可能，但这种issue建议投到pytorch或者ffmpeg那边，这个报错主要是找不到某个pyd文件

**Comment by XGXG114514** [comment]
> 有可能，但这种issue建议投到pytorch或者ffmpeg那边，这个报错主要是找不到某个pyd文件

但这个文件在对应文件夹里是存在的，就很奇怪

**Comment by anfogy** [comment]
> > 有可能，但这种issue建议投到pytorch或者ffmpeg那边，这个报错主要是找不到某个pyd文件
> 
> 但这个文件在对应文件夹里是存在的，就很奇怪

这就很神奇了，不懂

**Comment by XGXG114514** [comment]
> > > 有可能，但这种issue建议投到pytorch或者ffmpeg那边，这个报错主要是找不到某个pyd文件
> > 
> > 
> > 但这个文件在对应文件夹里是存在的，就很奇怪
> 
> 这就很神奇了，不懂

换了CJE模型，居然可以开始训练了，虽然训练的时候一直报这个错误，但原版vits好像也没用ffmpeg吧 就不知道训练出来怎么样了

**Comment by anfogy** [comment]
> > > > 有可能，但这种issue建议投到pytorch或者ffmpeg那边，这个报错主要是找不到某个pyd文件
> > > 
> > > 
> > > 但这个文件在对应文件夹里是存在的，就很奇怪
> > 
> > 
> > 这就很神奇了，不懂
> 
> 换了CJE模型，居然可以开始训练了，虽然训练的时候一直报这个错误，但原版vits好像也没用ffmpeg吧 就不知道训练出来怎么样了

那，恭喜你（？
虽然不知道怎么解决的，可以close了
