### ISSUE TITLE
ubuntu环境下运行到STEP 3 自动处理所有上传的数据时出错

### ISSUE THREAD

**Issue by Jerryym** [Plachtaa/VITS-fast-fine-tuning#370]
系统环境：ubuntu20.04
python版本：3.9
cuda版本：11.3

出错提示
```
/home/pai/lib/python3.9/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "/mnt/workspace/VITS-fast-fine-tuning/scripts/short_audio_transcribe.py", line 4, in <module>
    import torchaudio
  File "/home/pai/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/pai/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/pai/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/mnt/workspace/VITS-fast-fine-tuning/scripts/resample.py", line 4, in <module>
    import torchaudio
  File "/home/pai/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/pai/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/pai/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/pai/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

**Comment by Plachtaa** [comment]
cuda版本问题，请安装对应版本的torch和cuda，如果是torch 1.13.1请使用cuda11.6或11.7

**Comment by Jerryym** [comment]
> cuda版本问题，请安装对应版本的torch和cuda，如果是torch 1.13.1请使用cuda11.6或11.7

好的，我试试

**Comment by Jerryym** [comment]
系统环境：ubuntu20.04
python版本：3.9.15
torch版本：1.12.1
cuda版本：11.3
数据集：100个短音频

现在在 **STEP 3 自动处理所有上传的数据** 会出现以下问题
```
/home/pai/lib/python3.9/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "/mnt/workspace/VITS-fast-fine-tuning/scripts/short_audio_transcribe.py", line 55, in <module>
    speaker_names = list(os.walk(parent_dir))[0][1]
IndexError: list index out of range
```

**Comment by Jerryym** [comment]
升级cuda至11.7，torch升级至1.13.1后，问题已解决

**Comment by SRbone** [comment]
win10
python 3.8
torch  2.0.1+cu118
STEP3 short_audio_transcribe.py 也出现类似问题：

python .\short_audio_transcribe.py --languages CJE --whisper_size large
D:\python\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stabl
e/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File ".\short_audio_transcribe.py", line 55, in <module>
    speaker_names = list(os.walk(parent_dir))[0][1]
IndexError: list index out of range


请问 parent_dir中短音频的文件路径是: ./custom_character_voice/100.wav  没错吧？

**Comment by RacerChen** [comment]
```(base) F:\UP\VITS>python scripts/long_audio_transcribe.py --languages "{C}" --whisper_size large
Traceback (most recent call last):
  File "F:\UP\VITS\scripts\long_audio_transcribe.py", line 11, in <module>
    filelist = list(os.walk(parent_dir))[0][2]
               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range```
same here

**Comment by RacerChen** [comment]
@HaSaKiYasuooo 我按照文档{name}_{randomIndex}.wav，放在了raw_audio目录下，还是报这个错误呢

**Comment by snow-008** [comment]
我这个在colab上运行出现这个问题
Traceback (most recent call last): File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 41, in <module> result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options) File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 323, in transcribe add_word_timestamps( File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 298, in add_word_timestamps alignment = find_alignment(model, tokenizer, text_tokens, mel, num_frames, **kwargs) File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 210, in find_alignment weights = median_filter(weights, medfilt_width) File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 40, in median_filter result = median_filter_cuda(x, filter_width) File "/usr/local/lib/python3.10/dist-packages/whisper/triton_ops.py", line 107, in median_filter_cuda kernel[(grid,)](y, x, x.stride(-2), y.stride(-2), BLOCK_SIZE=BLOCK_SIZE) File "<string>", line 63, in kernel File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 425, in compile so_path = make_stub(name, signature, constants) File "/usr/local/lib/python3.10/dist-packages/triton/compiler/make_launcher.py", line 39, in make_stub so = _build(name, src_path, tmpdir) File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 61, in _build cuda_lib_dirs = libcuda_dirs() File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 30, in libcuda_dirs assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg AssertionError: libcuda.so cannot found!
