### ISSUE TITLE
本地训练报错

### ISSUE THREAD

**Issue by 2579356425** [Plachtaa/VITS-fast-fine-tuning#374]
```
WARNING:OUTPUT_MODEL:/VITS-fast-fine-tuning-main1 is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Bucket warning
Failed to find latest checkpoint, loading G_0.pth...
Train with pretrained model...
INFO:OUTPUT_MODEL:emb_g.weight is not in the checkpoint
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 352, in <module>
    main()
  File "finetune_speaker_v2.py", line 56, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/root/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/VITS-fast-fine-tuning-main1/finetune_speaker_v2.py", line 104, in run
    _, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "G_latest.pth"), net_g, None)
  File "/VITS-fast-fine-tuning-main1/utils.py", line 215, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/VITS-fast-fine-tuning-main1/finetune_speaker_v2.py", line 111, in run
    _, _, _, epoch_str = utils.load_checkpoint("./pretrained_models/G_0.pth", net_g, None)
  File "/VITS-fast-fine-tuning-main1/utils.py", line 177, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "/root/anaconda3/envs/vits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([68, 192]) from checkpoint, the shape in current model is torch.Size([52, 192]).
```
我在本地部署并训练，换了一批数据（之前用这批数据训练过），再次训练报错，这是什么问题

**Comment by 2579356425** [comment]
数据是从LJSpeech和Librispeech中选取的一部分，LJSpeech选了五千多条，Librispeech选了一个说话人的，时长均在2-10秒

**Comment by anfogy** [comment]
不知道原因，不过重新配置一次应该就可以了，之前遇到过

**Comment by shirubei** [comment]
因为各语言对应的模型文件是不一样的。
确保pretrained_models目录下的G_0.pth和D_0.pth跟你现在要训练的模型的语言是一致的应该就能解决。

在执行以下命令的时候，你得指定PRETRAINED_MODEL到底用什么，比如，C，或者CJE，或者CJ
python scripts/long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
python scripts/short_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large

一旦你指定了PRETRAINED_MODEL的值，那pretrained_models目录下的G_0.pth和D_0.pth就要用对应的文件。
