### ISSUE TITLE
## #STEP 4运行报错

### ISSUE THREAD

**Issue by xingkongyihetu** [Plachtaa/VITS-fast-fine-tuning#377]
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['zh_ja_mixture_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 4, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'speakers': {'Academia': 0, 'specialweek': 1, 'zhongli': 2, 'vctk': 3}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'A', 'E', 'I', 'N', 'O', 'Q', 'U', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'ʃ', 'ʧ', 'ʦ', 'ɯ', 'ɹ', 'ə', 'ɥ', '⁼', 'ʰ', '`', '→', '↓', '↑', ' '], 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 100000, 'cont': True, 'drop_speaker_embed': False, 'train_with_pretrained_model': True, 'preserved': 4}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Failed to find latest checkpoint, loading G_0.pth...5
Train with pretrained model...3
INFO:OUTPUT_MODEL:emb_g.weight is not in the checkpoint
INFO:OUTPUT_MODEL:Loaded checkpoint './pretrained_models/G_0.pth' (iteration None)
Train with pretrained model...7
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 374, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/autodl-tmp/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 103, in run
    _, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "G_latest.pth"), net_g, None)
  File "/root/autodl-tmp/VITS-fast-fine-tuning/utils.py", line 215, in latest_checkpoint_path
    x = f_list[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 112, in run
    _, _, _, epoch_str = utils.load_checkpoint("./pretrained_models/D_0.pth", net_d, None)
  File "/root/autodl-tmp/VITS-fast-fine-tuning/utils.py", line 150, in load_checkpoint
    checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by xingkongyihetu** [comment]
解决了，是因为AutoDL上下载予训练模板不稳定，导致基模板内容为空，形成假模板，使其报错。
解决方法一：简单的就是自己上传一下放在合适的位置，并且验证一下G模型和D模型名字是否有问题，如果有及得请将G模型和D模型分别重命名为G_0.pth和D_0.pth。
解决方法二：使用AutoDL自带的学术资源加速方法，[学术资源加速教学网站](https://www.autodl.com/docs/network_turbo/)，可以让下载稳定。
解决方法三：使用欧皇气数，下载不出错，使用不没问题。
