### ISSUE TITLE
运行时出现存储空间不足问题

### ISSUE THREAD

**Issue by ice-lynn** [Plachtaa/VITS-fast-fine-tuning#397]
运行训练代码时，总是报错OSError: [Errno 28] No space left on device，但实际上空间内存足够。这是因为什么原因呢

(vits) root@3a5036f18e77:~/VITS-fast-fine-tuning# export CUDA_VISIBLE_DEVICES=0 && python finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs "1000" --drop_speaker_embed True
/root/miniconda3/envs/vits/lib/python3.8/site-packages/joblib/_multiprocessing_helpers.py:46: UserWarning: [Errno 28] No space left on device.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 372, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/root/miniconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 182, in start_processes
    error_queue = mp.SimpleQueue()
  File "/root/miniconda3/envs/vits/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/root/miniconda3/envs/vits/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/root/miniconda3/envs/vits/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/root/miniconda3/envs/vits/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/root/miniconda3/envs/vits/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
**_OSError: [Errno 28] No space left on device_**

空间内存：
(vits) root@3a5036f18e77:~/VITS-fast-fine-tuning# df -lh
Filesystem      Size  Used Avail Use% Mounted on
overlay         879G  409G  426G  50% /
tmpfs            64M     0   64M   0% /dev
shm              64M   64M     0 100% /dev/shm
/dev/sda2       879G  409G  426G  50% /etc/hosts
tmpfs            32G   12K   32G   1% /proc/driver/nvidia
tmpfs           6.3G  3.5M  6.3G   1% /run/nvidia-persistenced/socket
udev             32G     0   32G   0% /dev/nvidia0

**Comment by anfogy** [comment]
[试试这个](https://stackoverflow.com/questions/6998083/python-causing-ioerror-errno-28-no-space-left-on-device-results-32766-h)

**Comment by hedane** [comment]
shm 64M 64M 0 100% /dev/shm

就是这个不够

**Comment by ice-lynn** [comment]
> shm 64M 64M 0 100% /dev/shm
> 
> 就是这个不够

你是对的，已经解决问题啦
