### ISSUE TITLE
 Getting requirements to build wheel ... error

### ISSUE THREAD

**Issue by salier** [Plachtaa/VITS-fast-fine-tuning#43]
如图
pip install -r requirements.txt执行失败
下载和pip是没啥问题 好像是那个构建炸了
没看出来是少了什么
可以帮我看看哪里出了问题嘛？非常感谢
![image](https://user-images.githubusercontent.com/28691601/222198358-6a787c56-3725-4cc9-b356-cc9acba1489b.png)
F:\vits\VITS-fast-fine-tuning-main>pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting Cython
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/3a/e59db3769dee48409c759a88b62cd605324e05d396e10af0a065adc956ad/Cython-0.29.33-py2.py3-none-any.whl (987 kB)
Collecting librosa
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/2e/80370da514096c6190f8913668198380ea09c2d252cfa4e85a9c096d3b40/librosa-0.10.0-py3-none-any.whl (252 kB)
Requirement already satisfied: numpy in c:\python\lib\site-packages (from -r requirements.txt (line 3)) (1.24.2)
Collecting scipy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/e3/b06ac3738bf365e89710205a471abe7dceec672a51c244b469bc5d1291c7/scipy-1.10.1-cp310-cp310-win_amd64.whl (42.5 MB)
Collecting tensorboard
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8d/71/75fcfab1ff98e3fad240f760d3a6b5ca6bdbcc5ed141fb7abd35cf63134c/tensorboard-2.12.0-py3-none-any.whl (5.6 MB)
Collecting torch
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/33/bd/e174e6737daba03f8eaa7c051b9971d361022eb37b86cbe5db0b08cab00e/torch-1.13.1-cp310-cp310-win_amd64.whl (162.6 MB)
Collecting torchvision
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b8/e0/edf3d41324c27f246abe1a4942227c6abe44fb2e62d35807178acb1355ba/torchvision-0.14.1-cp310-cp310-win_amd64.whl (1.1 MB)
Collecting torchaudio
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/48/0b/99c8f10fccccef0279acdfa2a6c27dd19d7eab3be1fd8fa59c09ad06b436/torchaudio-0.13.1-cp310-cp310-win_amd64.whl (2.0 MB)
Collecting unidecode
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/be/ea/90e14e807da5a39e5b16789acacd48d63ca3e4f23dfa964a840eeadebb13/Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting pyopenjtalk
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b4/80/a2505a37937fcd108b7c1ab66f7d1d48560525b1da71993860d11095a286/pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "C:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Night\AppData\Local\Temp\pip-build-env-xmh3jw0x\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Night\AppData\Local\Temp\pip-build-env-xmh3jw0x\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Night\AppData\Local\Temp\pip-build-env-xmh3jw0x\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Night\AppData\Local\Temp\pip-build-env-xmh3jw0x\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\python\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\python\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\python\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Plachtaa** [comment]
本地环境是很难装的，所以建议用colab notebook
这个是pyopenjtalk的问题
如果一定要装在本地的话，很抱歉因为时间关系后续我也无法为你提供进一步帮助，相关问题请自行谷歌解决。

**Comment by salier** [comment]
感谢提醒.已经配完了
但是好像云端的启动和本地启动不太一样把？
从step3开始就有点摸不到头脑了
我这本地不知道如何启动
启动的配置文件是哪一个呢？

**Comment by sunlihao2018** [comment]
我也遇到过这个问题
我解决的方法是安装cmake
在Ubuntu环境下，例如：sudo apt install cmake
Windows装个cmake应该也可以

**Comment by positive666** [comment]
配置cmake的环境变量后，打开VS的xnative TOOLS 激活你的环境变量在那个窗口安装
