### ISSUE TITLE
在训练的时候遇到以下问题

### ISSUE THREAD

**Issue by hansonli** [Plachtaa/VITS-fast-fine-tuning#430]
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 372, in <module>
    main()
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 154, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 262, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "/content/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 331, in evaluate
    y_hat, attn, mask, *_ = generator.module.infer(x, x_lengths, speakers, max_len=1000)
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by AnyaCoder** [comment]
是多卡训练吗？这个项目要求至少2卡 都 > 12G。

**Comment by hansonli** [comment]
> 是多卡训练吗？这个项目要求至少2卡 都 > 12G。

完了 我是笔记本集成显卡跑的……

**Comment by AnyaCoder** [comment]
> > 是多卡训练吗？这个项目要求至少2卡 都 > 12G。
> 
> 完了 我是笔记本集成显卡跑的……

建议上云服务器训练，笔记本是不够的
