### ISSUE TITLE
如何添加自己训练的角色

### ISSUE THREAD

**Issue by light100bc** [Plachtaa/VITS-fast-fine-tuning#449]
能问一下我训练好之后怎么添加到UI界面嘛，finetune_speaker.json是会生成一个新的嘛？为什么我训练好之后没有这个json'文件，UI界面也没有自己训练的新角色

**Comment by anfogy** [comment]
你没保存

**Comment by AnyaCoder** [comment]
没改就手动改一下speakers
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/122108331/9eaa08bf-1914-4d93-a544-8bbf0f810f8a)

**Comment by light100bc** [comment]
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 251 to ././OUTPUT_MODEL/G_latest.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 251 to ././OUTPUT_MODEL/D_latest.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 251 to ././OUTPUT_MODEL/G_31000.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 251 to ././OUTPUT_MODEL/D_31000.pth
oldest_checkpoint_path:././OUTPUT_MODEL/G_30600.pth
oldest_checkpoint_path:././OUTPUT_MODEL/D_30600.pth
remove ././OUTPUT_MODEL/G_30600.pth
remove ././OUTPUT_MODEL/D_30600.pth
Maximum epoch reached, closing training...
  0%|                                                                                           | 0/124 [00:09<?, ?it/s]None
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 372, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/maikaka/anaconda3/envs/test/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/maikaka/anaconda3/envs/test/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/maikaka/anaconda3/envs/test/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

我finetune最后结束后是这样的，是这个出错的原因嘛。。。但不知道该怎么办T-T。有人能帮忙解释一下该怎么办嘛

**Comment by light100bc** [comment]
> 你没保存

OUTPUT_MODEL只有训练好的模型，没有finetune_speaker.json。只有config里有原先的finetune_speaker.json。这个json我是要自己改嘛。

**Comment by wmlgl** [comment]
cp ./configs/modified_finetune_speaker.json ./finetune_speaker.json
python3 VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True

是在modified_finetune_speaker.json
