### ISSUE TITLE
步骤三报错

### ISSUE THREAD

**Issue by Zexoneoft** [Plachtaa/VITS-fast-fine-tuning#46]
使用视频链接上传，一直报错。也尝试过在谷歌云盘上传长音频，也报错，错误信息相同。

denoised_audio 和 /separated/htdemucs文件夹中无文件

使用txt文件:
[characters.txt](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10871315/characters.txt)
报错信息:
```[MoviePy] Writing audio in ./raw_audio/TeacherShen_37232.wav
100%|██████████| 59539/59539 [00:28<00:00, 2061.93it/s][MoviePy] Done.

[MoviePy] Writing audio in ./raw_audio/TeacherShen_62695.wav
100%|██████████| 47538/47538 [00:22<00:00, 2101.01it/s][MoviePy] Done.

[MoviePy] Writing audio in ./raw_audio/TeacherShen_881627.wav
100%|██████████| 67062/67062 [00:34<00:00, 1969.92it/s][MoviePy] Done.

Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Downloading: "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th" to /root/.cache/torch/hub/checkpoints/955717e8-8726e21a.th
100% 80.2M/80.2M [00:06<00:00, 13.3MB/s]
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/VITS-fast-fine-tuning/separated/htdemucs
Separating track raw_audio/TeacherShen_881627.wav
100%|██████████████████████████████████████████████████████████████████████| 3042.0/3042.0 [02:25<00:00, 20.88seconds/s]
Killed
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/VITS-fast-fine-tuning/separated/htdemucs
Separating track raw_audio/TeacherShen_62695.wav
100%|████████████████████████████████████████████████████████████████████| 2158.65/2158.65 [01:45<00:00, 20.50seconds/s]
Killed
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/VITS-fast-fine-tuning/separated/htdemucs
Separating track raw_audio/TeacherShen_37232.wav
100%|██████████████████████████████████████████████████████████████████████| 2702.7/2702.7 [02:11<00:00, 20.55seconds/s]
Killed
Traceback (most recent call last):
  File "denoise_audio.py", line 12, in <module>
    wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/usr/local/lib/python3.8/dist-packages/torchaudio/io/_compat.py", line 103, in load_audio
    s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
RuntimeError: Failed to open the input "./separated/htdemucs/TeacherShen_881627/vocals.wav" (No such file or directory).
2023-03-02 12:30:14.745081: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-02 12:30:18.161604: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-02 12:30:18.161791: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-02 12:30:18.161814: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
2023-03-02 12:30:56.773756: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-02 12:30:57.789432: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-02 12:30:57.789562: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-02 12:30:57.789583: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.```

**Comment by Plachtaa** [comment]
可能是音频太长导致demucs崩了，之前有人遇到过这个问题，后来手动切到每条15分钟就修复了
