### ISSUE TITLE
【本地运行错误】Failed to execute script 'inference' due to unhandled exception!

### ISSUE THREAD

**Issue by xiaomi0530** [Plachtaa/VITS-fast-fine-tuning#470]
在本地运行inference.exe，文件配置都没有问题，但是报错（如下），也没有网页打开。望帮助，谢谢。

Traceback (most recent call last):
  File "inference.py", line 97, in <module>
  File "utils.py", line 19, in load_checkpoint
AssertionError
[14352] Failed to execute script 'inference' due to unhandled exception!

**Comment by anfogy** [comment]
py版本不对吧

**Comment by zzapbj** [comment]
用自己训练后的模型的config.json和G_latest.pth可以正常使用, config.json要改名为./finetune_speaker.json ，然后就能解决正常启动了
