### ISSUE TITLE
DataLoader的TextAudioSpeakerCollate错误

### ISSUE THREAD

**Issue by yanfeiwong** [Plachtaa/VITS-fast-fine-tuning#51]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\VITS\finetune_speaker_v2.py", line 134, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "G:\VITS\finetune_speaker_v2.py", line 242, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "G:\VITS\finetune_speaker_v2.py", line 265, in evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(eval_loader):
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Yan\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "G:\VITS\data_utils.py", line 159, in __call__
    spec_padded[i, :, :spec.size(1)] = spec
RuntimeError: expand(torch.FloatTensor{[2, 513, 478]}, size=[513, 513]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)

**Comment by yanfeiwong** [comment]
已经找到问题，数据集里的个别wav文件是双通道导致的
