### ISSUE TITLE
训练的时候报错了， 这个是什么原因呢？ 是因为硬件吗

### ISSUE THREAD

**Issue by pifeifei** [Plachtaa/VITS-fast-fine-tuning#516]
```
\VITS-fast-fine-tuning>python finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs 1000 --drop_speaker_embed True


INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['cjke_cleaners2'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 4, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'N', 'Q', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ɑ', 'æ', 'ʃ', 'ʑ', 'ç', 'ɯ', 'ɪ', 'ɔ', 'ɛ', 'ɹ', 'ð', 'ə', 'ɫ', 'ɥ', 'ɸ', 'ʊ', 'ɾ', 'ʒ', 'θ', 'β', 'ŋ', 'ɦ', '⁼', 'ʰ', '`', '^', '#', '*', '=', 'ˈ', 'ˌ', '→', '↓', '↑', ' '], 'speakers': {'xinyi': 0, 'specialweek': 1, 'zhongli': 2, 'vctk': 3}, 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 1000, 'cont': False, 'drop_speaker_embed': True, 'train_with_pretrained_model': True, 'preserved': 4}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.


Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 372, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "H:\git\7-python\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 92, in run
    net_g = SynthesizerTrn(
  File "H:\git\7-python\VITS-fast-fine-tuning\models.py", line 447, in __init__
    self.dec = Generator(inter_channels, resblock, resblock_kernel_sizes, resblock_dilation_sizes, upsample_rates, upsample_initial_channel, upsample_kernel_sizes, gin_channels=gin_channels)
  File "H:\git\7-python\VITS-fast-fine-tuning\models.py", line 262, in __init__
    self.resblocks.append(resblock(ch, k, d))
  File "H:\git\7-python\VITS-fast-fine-tuning\modules.py", line 201, in __init__
    weight_norm(Conv1d(channels, channels, kernel_size, 1, dilation=1,
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\nn\utils\weight_norm.py", line 109, in weight_norm
    WeightNorm.apply(module, name, dim)
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\nn\utils\weight_norm.py", line 50, in apply
    setattr(module, name, fn.compute_weight(module))
  File "D:\ProgramFiles\anaconda3\envs\py38\lib\site-packages\torch\nn\utils\weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1835008 bytes.

```

我内存是 32G ,  用的 p2000 显卡

**Comment by longshiming** [comment]
用Google Colab训练的，报和你上面一样的错，UnboundLocalError: local variable 'x' referenced before assignment，不知道原因

**Comment by Barry1208** [comment]
请问解决了吗？
