### ISSUE TITLE
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'

### ISSUE THREAD

**Issue by Coresvin** [Plachtaa/VITS-fast-fine-tuning#52]
=============================================================
ni↓↑xɑʊ↓↑.
 length:10
 length:10
Traceback (most recent call last):
  File "gradio\routes.py", line 380, in run_predict
    event_id=event_id,
  File "gradio\blocks.py", line 1018, in process_api
    fn_index, inputs, iterator, request, event_id
  File "gradio\blocks.py", line 836, in call_function
    fn, *processed_input, limiter=self.limiter
  File "anyio\to_thread.py", line 32, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "inference.py", line 42, in tts_fn
  File "models_infer.py", line 370, in infer
  File "torch\nn\modules\module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesizerTrn' object has no attribute 'emb_g'
============================================================

程序报错，colab上导出前是正常的，导出后到本地就报错

**Comment by Plachtaa** [comment]
本地应用太老了不支持单人模型，过两天更新

**Comment by Coresvin** [comment]
我把人物id改成0勉强可以用了

**Comment by Coresvin** [comment]
就是finetune_speaker.json
里的
  "speakers": {
    "A": 0
  }
