### ISSUE TITLE
STEP 3 错误

### ISSUE THREAD

**Issue by bland3** [Plachtaa/VITS-fast-fine-tuning#531]
Separating track raw_audio/Sample_1.wav
100%|██████████████████████████████████████████████████████████████████████| 579.15/579.15 [00:28<00:00, 20.10seconds/s]
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
100%|██████████████████████████████████████| 2.87G/2.87G [00:30<00:00, 101MiB/s]
transcribing ./denoised_audio/Sample_1.wav...

Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 41, in <module>
    result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 323, in transcribe
    add_word_timestamps(
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 298, in add_word_timestamps
    alignment = find_alignment(model, tokenizer, text_tokens, mel, num_frames, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 210, in find_alignment
    weights = median_filter(weights, medfilt_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 40, in median_filter
    result = median_filter_cuda(x, filter_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/triton_ops.py", line 107, in median_filter_cuda
    kernel[(grid,)](y, x, x.stride(-2), y.stride(-2), BLOCK_SIZE=BLOCK_SIZE)
  File "<string>", line 63, in kernel
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 30, in libcuda_dirs
    assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!

Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

**Comment by qianmu231** [comment]
在step3前运行
!export LC_ALL="en_US.UTF-8"
!export LD_LIBRARY_PATH="/usr/lib64-nvidia"
!export LIBRARY_PATH="/usr/local/cuda/lib64/stubs"
!ldconfig /usr/lib64-nvidia
试试

**Comment by bland3** [comment]
是版本问题，已解决

**Comment by alanyuwenche** [comment]
如何解決版本問題可以寫詳細點嗎? 感謝

**Comment by wu71121** [comment]
> 是版本问题，已解决

請問你怎麼解決的

**Comment by jodykwong** [comment]
同问

**Comment by jodykwong** [comment]
> 是版本问题，已解决
同问

**Comment by jodykwong** [comment]
> 是版本问题，已解决

同问

**Comment by jodykwong** [comment]
> 是版本问题，已解决

同问，是怎么解决的。我用colab还是有这个问题

**Comment by iou3344** [comment]
> 在step3前运行 !export LC_ALL="en_US.UTF-8" !export LD_LIBRARY_PATH="/usr/lib64-nvidia" !export LIBRARY_PATH="/usr/local/cuda/lib64/stubs" !ldconfig /usr/lib64-nvidia 试试

很有效！另外，请问在colab微调成功后，怎么直接保存和调用这个结果呢？不会每次使用都要从头来做一遍吧？这太恐怖了~

**Comment by qianmu231** [comment]
> > 在step3前运行 !export LC_ALL="en_US.UTF-8" !export LD_LIBRARY_PATH="/usr/lib64-nvidia" !export LIBRARY_PATH="/usr/local/cuda/lib64/stubs" !ldconfig /usr/lib64-nvidia 试试
> 
> 很有效！另外，请问在colab微调成功后，怎么直接保存和调用这个结果呢？不会每次使用都要从头来做一遍吧？这太恐怖了~

见#345
和#426

**Comment by zhangningxin** [comment]
> 在step3前运行 !export LC_ALL="en_US.UTF-8" !export LD_LIBRARY_PATH="/usr/lib64-nvidia" !export LIBRARY_PATH="/usr/local/cuda/lib64/stubs" !ldconfig /usr/lib64-nvidia 试试

感谢 问题已解决

**Comment by realDSH** [comment]
> 在step3前运行 !export LC_ALL="en_US.UTF-8" !export LD_LIBRARY_PATH="/usr/lib64-nvidia" !export LIBRARY_PATH="/usr/local/cuda/lib64/stubs" !ldconfig /usr/lib64-nvidia 试试

请问是不是失效了?step3前添加后step3还是跑不起来
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/60806652/f2ddcb03-e8bd-4f77-a208-9da6efab4795)

**Comment by Clearpole** [comment]
> 在step3前运行 !export LC_ALL="en_US.UTF-8" !export LD_LIBRARY_PATH="/usr/lib64-nvidia" !export LIBRARY_PATH="/usr/local/cuda/lib64/stubs" !ldconfig /usr/lib64-nvidia 试试

好强！跑起来了
