### ISSUE TITLE
运行【STEP 3 自动处理所有上传的数据】报错

### ISSUE THREAD

**Issue by jodykwong** [Plachtaa/VITS-fast-fine-tuning#535]
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/VITS-fast-fine-tuning/separated/htdemucs
Separating track raw_audio/ZOOM_001.wav
100%|████████████████████████████████████████████████████████████████████████| 234.0/234.0 [00:12<00:00, 18.25seconds/s]
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
transcribing ./denoised_audio/ZOOM_001.wav...

Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 41, in <module>
    result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 323, in transcribe
    add_word_timestamps(
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 298, in add_word_timestamps
    alignment = find_alignment(model, tokenizer, text_tokens, mel, num_frames, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 210, in find_alignment
    weights = median_filter(weights, medfilt_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 40, in median_filter
    result = median_filter_cuda(x, filter_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/triton_ops.py", line 107, in median_filter_cuda
    kernel[(grid,)](y, x, x.stride(-2), y.stride(-2), BLOCK_SIZE=BLOCK_SIZE)
  File "<string>", line 63, in kernel
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 30, in libcuda_dirs
    assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!

**Comment by jodykwong** [comment]
尝试使用最新版本的whisper20231117，依然解决不了问题

**Comment by tom20180101** [comment]
AssertionError: libcuda.so cannot found!   这个貌似是cuda的问题，确认下cuda正确安装了

**Comment by jodykwong** [comment]
> AssertionError: libcuda.so cannot found! 这个貌似是cuda的问题，确认下cuda正确安装了

请问你是用哪个版本的cuda

**Comment by Wenbobobo** [comment]
我也遇到了，是长音频
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
transcribing ./denoised_audio/Cyan_34.wav...

Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 41, in <module>
    result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 323, in transcribe
    add_word_timestamps(
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 298, in add_word_timestamps
    alignment = find_alignment(model, tokenizer, text_tokens, mel, num_frames, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 210, in find_alignment
    weights = median_filter(weights, medfilt_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 40, in median_filter
    result = median_filter_cuda(x, filter_width)
  File "/usr/local/lib/python3.10/dist-packages/whisper/triton_ops.py", line 107, in median_filter_cuda
    kernel[(grid,)](y, x, x.stride(-2), y.stride(-2), BLOCK_SIZE=BLOCK_SIZE)
  File "<string>", line 63, in kernel
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/usr/local/lib/python3.10/dist-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 30, in libcuda_dirs
    assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
AssertionError: libcuda.so cannot found!
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

**Comment by tom20180101** [comment]
@jodykwong    我的cuda是11.7的，显卡驱动是 535.129.03

**Comment by anfogy** [comment]
可以去看看官方有人投的[Issue](https://github.com/pytorch/pytorch/issues/107960)

**Comment by CarlosDJY** [comment]
@Wenbobobo 
经尝试有效（训练音频：3个长音频）：
在step3上方插入代码块：
```
!export LC_ALL="en_US.UTF-8"
!export LD_LIBRARY_PATH=”/usr/lib64-nvidia“ 
!export LIBRARY_PATH=”/usr/local/cuda/lib64/stubs“
!ldconfig /usr/lib64-nvidia
```
来源：[https://github.com/pytorch/pytorch/issues/107960](url)
感谢 @anfogy 指路
