### ISSUE TITLE
step4出错

### ISSUE THREAD

**Issue by HDUysz** [Plachtaa/VITS-fast-fine-tuning#537]
我在训练的时候观察loss，感觉已经符合预期并提前中断了训练。
```
#@markdown ### 微调完成后，在这里尝试效果。
#@markdown ### 运行后会输出一个public URL, 点击进入网页版UI以使用模型
#@markdown ### Try out TTS & VC quality here after fine-tuning is finished.
!cp ./configs/modified_finetune_speaker.json ./finetune_speaker.json
!python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True
```
在执行这个单元格的时候出现了如下报错：
```
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VC_inference.py", line 10, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/usr/local/lib/python3.10/dist-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "/usr/local/lib/python3.10/dist-packages/gradio/data_classes.py", line 14, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
```
他提示我缺少了RootModel，我在简单搜索了Issue之后没有找到相似的报错，是我提前中断训练的缘故吗？

**Comment by HDUysz** [comment]
> 这个问题我也遇到了，我的解决方法是把requriement的pydantic改成1.10.11然后另外加上!python -m pip install gradio==3.48.0

按照你的方法解决了问题，感谢你的解答，谢谢。
