### ISSUE TITLE
step3，colab报错 

### ISSUE THREAD

**Issue by reyiwuhan** [Plachtaa/VITS-fast-fine-tuning#543]
transcribing ./denoised_audio/MinatoAqua_1.wav... Traceback (most recent call last): File "/content/VITS-fast-fine-tuning/scripts/long_audio_transcribe.py", line 41, in <module> result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options) File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 323, in transcribe add_word_timestamps( File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 298, in add_word_timestamps alignment = find_alignment(model, tokenizer, text_tokens, mel, num_frames, **kwargs) File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 210, in find_alignment weights = median_filter(weights, medfilt_width) File "/usr/local/lib/python3.10/dist-packages/whisper/timing.py", line 40, in median_filter result = median_filter_cuda(x, filter_width) File "/usr/local/lib/python3.10/dist-packages/whisper/triton_ops.py", line 107, in median_filter_cuda kernel[(grid,)](y, x, x.stride(-2), y.stride(-2), BLOCK_SIZE=BLOCK_SIZE) File "<string>", line 63, in kernel File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 425, in compile so_path = make_stub(name, signature, constants) File "/usr/local/lib/python3.10/dist-packages/triton/compiler/make_launcher.py", line 39, in make_stub so = _build(name, src_path, tmpdir) File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 61, in _build cuda_lib_dirs = libcuda_dirs() File "/usr/local/lib/python3.10/dist-packages/triton/common/build.py", line 30, in libcuda_dirs assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg AssertionError: libcuda.so cannot found! Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links. this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.
一直卡在第三步

**Comment by xw2018** [comment]
是不是colab的GPU使用时间到了，运行一下第一步的nvidia-smi看看GPU能不能用
