### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'

### ISSUE THREAD

**Issue by KMGsiye** [Plachtaa/VITS-fast-fine-tuning#546]
在本地化train中，前十步都正常运行好了。（使用VS2022）
在第11步执行python finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs "100" --drop_speaker_embed True时，一直报错：
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 29, in <module>
    from models import (
  File "E:\@Code\VS file\VITS-fast-fine-tuning-main\models.py", line 10, in <module>
    import monotonic_align
  File "E:\@Code\VS file\VITS-fast-fine-tuning-main\monotonic_align\__init__.py", line 3, in <module>
    from .monotonic_align.core import maximum_path_c
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align.core'
拿FastVitsV20中的相应文件夹替换了也不行。
请教怎么解决，万分感谢

**Comment by xw2018** [comment]
可能是monotonic_align没有装好，建议重装monotonic_align

**Comment by fesolla** [comment]
你把個兩個文件移到  .\VITS-fast-fine-tuning\monotonic_align\monotonic_align這裡面去試試看
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/53915025/aeba3ab3-4cbc-497f-ab3c-37174e2fda5a)
