### ISSUE TITLE
关于ffmpeg拓展的问题，找不到4、5、6版本

### ISSUE THREAD

**Issue by YamakiYume** [Plachtaa/VITS-fast-fine-tuning#553]
本地部署时，之前步骤一切正常，但一旦到训练阶段，就会不停报错关于ffmpeg拓展与调用等问题，每次的训练步骤是可以继续进行的，但最终结果相当糟糕。我有可以使用的ffmpeg编译完成的exe文件且环境配置正常。具体报错如下：
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 5.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 5 extension.
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 4.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 4 extension.
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\__init__.py", line 89, in <module>
    _FFMPEG_EXT = _init_ffmpeg()
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 162, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers, show_error)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 132, in _find_ffmpeg_extension
    raise ImportError(f"Failed to intialize FFmpeg extension. Tried versions: {ffmpeg_vers}")
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4']
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 6 extension.
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 5.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 5 extension.
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension.utils:Attempting to load FFmpeg version 4.
DEBUG:torchaudio._extension.utils:Failed to load FFmpeg 4 extension.
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError
DEBUG:torchaudio._extension:Failed to initialize ffmpeg bindings
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\__init__.py", line 89, in <module>
    _FFMPEG_EXT = _init_ffmpeg()
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 162, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers, show_error)
  File "D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torchaudio\_extension\utils.py", line 132, in _find_ffmpeg_extension
    raise ImportError(f"Failed to intialize FFmpeg extension. Tried versions: {ffmpeg_vers}")
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4']
D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\SpectralOps.cpp:868.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
D:\Anaconda\Anaconda\envs\data_sci\lib\site-packages\torch\functional.py:650: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
请问这是什么问题，应该如何解决？

**Comment by hbwliao** [comment]
你装的FFmpeg的version是多少呢

**Comment by cythc** [comment]
同样的问题 ffmpeg6.1.1

**Comment by amoslue** [comment]
> 同样的问题 ffmpeg6.1.1

请问最终怎么解决的呢？

**Comment by wlsekd** [comment]
try ```conda install -c conda-forge 'ffmpeg<7'``` or ```conda install ffmpeg=6``` to install ffmpeg

more info at https://pytorch.org/audio/2.3.0/installation.html#dependencies
