### ISSUE TITLE
安裝Local訓練環境時出現問題

### ISSUE THREAD

**Issue by wingwing01** [Plachtaa/VITS-fast-fine-tuning#563]
PS G:\VITS-fast-fine-tuning> pip install --no-build-isolation -r requirements.txt
Collecting git+https://github.com/openai/whisper.git (from -r requirements.txt (line 25))
  Cloning https://github.com/openai/whisper.git to c:\users\ngwin\appdata\local\temp\pip-req-build-8_lzbwit
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git 'C:\Users\ngwin\AppData\Local\Temp\pip-req-build-8_lzbwit'
  Resolved https://github.com/openai/whisper.git to commit ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
  Preparing metadata (pyproject.toml) ... done
Collecting Cython==0.29.21 (from -r requirements.txt (line 1))
  Downloading Cython-0.29.21-py2.py3-none-any.whl (974 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 974.2/974.2 kB 7.7 MB/s eta 0:00:00
Collecting librosa==0.9.2 (from -r requirements.txt (line 2))
  Using cached librosa-0.9.2-py3-none-any.whl (214 kB)
Collecting matplotlib==3.3.1 (from -r requirements.txt (line 3))
  Downloading matplotlib-3.3.1.tar.gz (38.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 28.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting scikit-learn==1.0.2 (from -r requirements.txt (line 4))
  Downloading scikit-learn-1.0.2.tar.gz (6.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 11.9 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Partial import of sklearn during the build process.
      <string>:128: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

      Traceback (most recent call last):
        File "C:\Users\ngwin\AppData\Local\Temp\pip-install-uclh_2cq\scikit-learn_fb86cb49827646149b644ac5a1b6f6c1\sklearn\_build_utils\__init__.py", line 28, in _check_cython_version
          import Cython
      ModuleNotFoundError: No module named 'Cython'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "D:\CONDA\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\CONDA\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\CONDA\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\CONDA\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "D:\CONDA\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "D:\CONDA\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 319, in <module>
        File "<string>", line 315, in setup_package
        File "D:\CONDA\Lib\site-packages\numpy\distutils\core.py", line 136, in setup
          config = configuration()
                   ^^^^^^^^^^^^^^^
        File "<string>", line 199, in configuration
        File "C:\Users\ngwin\AppData\Local\Temp\pip-install-uclh_2cq\scikit-learn_fb86cb49827646149b644ac5a1b6f6c1\sklearn\_build_utils\__init__.py", line 31, in _check_cython_version
          raise ModuleNotFoundError(message) from e
      ModuleNotFoundError: Please install Cython with a version >= 0.29.24 in order to build a scikit-learn from source.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tom20180101** [comment]
ModuleNotFoundError: No module named 'Cython'     in your error,  try pip install cython
