### ISSUE TITLE
【本地运行错误】AssertionError [12700] Failed to execute script 'inference' due to unhandled exception!

### ISSUE THREAD

**Issue by heibar119** [Plachtaa/VITS-fast-fine-tuning#569]
Traceback (most recent call last):
  File "inference.py", line 97, in <module>
  File "utils.py", line 19, in load_checkpoint
AssertionError
[12700] Failed to execute script 'inference' due to unhandled exception!

**Comment by hzy102332** [comment]
Loading model cost 0.390 seconds.
DEBUG:jieba:Loading model cost 0.390 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.
INFO:root:Loaded checkpoint './G_latest.pth' (iteration 184)
Traceback (most recent call last):
  File "inference.py", line 99, in <module>
AttributeError: 'list' object has no attribute 'keys'
[19728] Failed to execute script 'inference' due to unhandled exception!

**Comment by daoyuanzhai** [comment]
> Traceback (most recent call last): File "inference.py", line 97, in File "utils.py", line 19, in load_checkpoint AssertionError [12700] Failed to execute script 'inference' due to unhandled exception!

I got exactly the same error, did you figure out how to solve it?
