### ISSUE TITLE
求助~長短 audio 在開始訓練前有問題

### ISSUE THREAD

**Issue by davechan0204** [Plachtaa/VITS-fast-fine-tuning#573]
短 audio 的 file 已經放在 VITS-fast-fine-tuning\custom_character_voice\test_talk 內 , 檔案名是 test_talk_XX.wav
run :  
python scripts/short_audio_transcribe.py --languages CJE --whisper_size large

出現 :
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

在 VITS-fast-fine-tuning\custom_character_voice\test_talk 內會有 processed_XX.wav

***

長 audio 的 file 已經放在 VITS-fast-fine-tuning\raw_audio 內 , 檔案名是 test_talk_240126.wav
run :  
python scripts/long_audio_transcribe.py --languages CJE --whisper_size large

出現 :
Traceback (most recent call last):
  File "scripts/long_audio_transcribe.py", line 41, in <module>
    result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\site-packages\whisper\transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\PC_20221023\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

請問大家有解嗎? 如果有細節沒說可以問我

**Comment by davechan0204** [comment]
嗯...是我 ffmpeg 沒安裝好
