### ISSUE TITLE
What exactly is "user" in "Voice Conversion" tab?

### ISSUE THREAD

**Issue by zz-xx** [Plachtaa/VITS-fast-fine-tuning#72]
After training a model locally on Windows, Text-to-Speech works as expected. But while trying Voice Conversion with "user" as source speaker, following error is encountered. For other source speakers apart from "user" everything works. I am executing `python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth`  to launch gradio UI. Screenshot below can be checked for steps to reproduce error.
![Screenshot 2023-03-06 132316](https://user-images.githubusercontent.com/31221615/223051689-47629c94-c599-42eb-9382-d7e24d586203.png)

Traceback (most recent call last):
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\gradio\blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\gradio\blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "X:\__Python__\AI codes\vits-finetune\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "X:\__Python__\AI codes\vits-finetune\VITS-fast-fine-tuning\VC_inference.py", line 54, in vc_fn
    original_speaker_id = speaker_ids[original_speaker]
  File "X:\__Python__\AI codes\vits-finetune\VITS-fast-fine-tuning\utils.py", line 261, in __getitem__
    return getattr(self, key)
AttributeError: 'HParams' object has no attribute 'User'

**Comment by Plachtaa** [comment]
This is actually a remaining feature of an older version of training pipeline, which reserved a position for users to record their own voice and feed into the model. In the new training pipeline it is deprecated, but I forgot to remove the placeholder in the inference UI. Sorry about that😥

**Comment by zz-xx** [comment]
Thank you for your work on fine tuning. Had a hunch it was some leftover bug. If you don't mind I can create a pull request for that unless you've already fixed that.

**Comment by Plachtaa** [comment]
I think it is now fixed in `VC_inference.py` but not in the local webui package...... Did you get this error while running `VC_inference.py` locally?

**Comment by zz-xx** [comment]
Yes - `python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth`. But looks like you have fixed it in latest commit.
