### ISSUE TITLE
step3和step4

### ISSUE THREAD

**Issue by whyohy** [Plachtaa/VITS-fast-fine-tuning#84]
**_![UYNMD`6 )$TD9 5CUUK`IR8](https://user-images.githubusercontent.com/127364161/223893564-6f26e99a-5d2e-4689-9eaa-3fd1785a1fd8.png)_**：
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/preprocess_v2.py](https://localhost:8080/#) in <module>
     56 
     57         # STEP 2: modify config file
---> 58         with open("./configs/finetune_speaker.json", 'r', encoding='utf-8') as f:
     59             hps = json.load(f)
     60 

FileNotFoundError: [Errno 2] No such file or directory: './configs/finetune_speaker.json'

_**step4**_：
Reusing TensorBoard on port 6006 (pid 10179), started 0:03:41 ago. (Use '!kill 10179' to kill it.)
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['chinese_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 2, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', '；', '：', '，', '。', '！', '？', '-', '“', '”', '《', '》', '、', '（', '）', '…', '—', ' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '0', 'Ｂ', 'Ｐ'], 'speakers': {'dingzhen': 0, 'taffy': 1}, 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 40, 'drop_speaker_embed': True}
2023-03-09 01:26:04.086368: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
2023-03-09 01:26:05.650715: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-09 01:26:05.650890: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-09 01:26:05.650917: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.9/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 321, in <module>
    main()
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 73, in run
    train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps.data, symbols)
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/data_utils.py", line 24, in __init__
    self.audiopaths_sid_text = load_filepaths_and_text(audiopaths_sid_text)
  File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/utils.py", line 276, in load_filepaths_and_text
    with open(filename, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'final_annotation_train.txt'

**Comment by Plachtaa** [comment]
请问你运行了下载预训练模型那一步没有

**Comment by whyohy** [comment]
感谢大佬，重新试了一遍畅通无阻！以及 下载最新的Release包 是不是要把图片里的全下载？
![Uploading 5)B5]5F_ALLRVQEZ5WD7F(O.png…]()

**Comment by whyohy** [comment]
感谢大佬，重新试了一遍畅通无阻！以及 下载最新的Release包 
![5)B5 5F_ALLRVQEZ5WD7F(O](https://user-images.githubusercontent.com/127364161/223921675-12e1c7c2-9172-4eba-baac-55fa56ba491d.png)

**Comment by whyohy** [comment]
感谢大佬，重新试了一遍畅通无阻！以及 下载最新的Release包 是不是要把这三个全下载？
![5)B5 5F_ALLRVQEZ5WD7F(O](https://user-images.githubusercontent.com/127364161/223922056-b07b84db-b9e4-4478-ac07-26c23f1d661e.png)

**Comment by Plachtaa** [comment]
只下第一个.rar就行了

**Comment by whyohy** [comment]
![%4)65RY%KW%9}O3W}D6TBX1](https://user-images.githubusercontent.com/127364161/223957266-b5c6738b-e5fb-4c97-85b4-bb6f9a2b56d4.png)
inference退出前就这样

**Comment by whyohy** [comment]
从colab下载的时候没有G下划线latest，只有两个.json

**Comment by Plachtaa** [comment]
G_latest.pth是模型本体，肯定要下载下来呀🤣

**Comment by whyohy** [comment]
哈哈，不知道怎么搞的没下载到这个，现在豁然开朗了喵
