### ISSUE TITLE
在kaggle执行finetune_speaker_v2.py出现TypeError

### ISSUE THREAD

**Issue by sudafin** [Plachtaa/VITS-fast-fine-tuning#89]
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:8000 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:8000 (errno: 99 - Cannot assign requested address).
[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:8000 (errno: 99 - Cannot assign requested address).
  0%|                                                    | 0/45 [00:00<?, ?it/s]/opt/conda/lib/python3.7/site-packages/torch/functional.py:633: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/SpectralOps.cpp:801.)
  normalized, onesided, return_complex)
/opt/conda/lib/python3.7/site-packages/torch/functional.py:633: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/SpectralOps.cpp:801.)
  normalized, onesided, return_complex)
/opt/conda/lib/python3.7/site-packages/torch/functional.py:633: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/SpectralOps.cpp:801.)
  normalized, onesided, return_complex)
/opt/conda/lib/python3.7/site-packages/torch/functional.py:633: UserWarning: stft will soon require the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release. (Triggered internally at /usr/local/src/pytorch/aten/src/ATen/native/SpectralOps.cpp:801.)
  normalized, onesided, return_complex)
  0%|                                                    | 0/45 [00:23<?, ?it/s]
  0%|                                                    | 0/45 [00:23<?, ?it/s]
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 321, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/kaggle/working/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 136, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, None], None, None)
  File "/kaggle/working/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 170, in train_and_evaluate
    hps.data.mel_fmax)
  File "/kaggle/working/VITS-fast-fine-tuning/mel_processing.py", line 78, in spec_to_mel_torch
    mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
TypeError: mel() takes 0 positional arguments but 5 were given

**Comment by Plachtaa** [comment]
把librosa降到0.9.1试试

**Comment by sudafin** [comment]
> 
不行，kaggle好像不能安装0.9.1的版本

**Comment by Plachtaa** [comment]
那没有办法了，之前有人还专门发了pr把requirements里的librosa加上了版本限制来解决windows上同样的问题，kaggle只能说想办法装，或者看看新版本的函数要怎么重写

**Comment by hmtbgc** [comment]
遇到相同问题，降低librosa版本可以解决问题：
/home/workspace/VITS-fast-fine-tuning/mel_processing.py:96: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel_out = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
